### ISSUE TITLE
serratus-Aligner based off Alpine Linux

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#1]
The [current AMI image](https://github.com/ababaian/serratus/blob/master/ami/makeAligner.sh) for `serratus-Aligner` is based off of Amazon Linux 2 (9 Gb base image). Switching this to Alpine Linux (95 Mb base image; ~400 Mb with python + dev libs) will reduce storage overhead and load times.

Current issue is that Alpine Linux uses the libc `musl` and not `glibc`, and this causes dependency issues with `bowtie2` and `perl` (dependency). I would get a recurring error of `executable not found` with pre-compiled `bowtie2` and could not compile from source. See early version of above `makeAligner.sh` script to reproduce attempt via Alpine Linux.

**Comment by jefftaylor42** [comment]
Just wondering if you expect load time to be a bottleneck?  Every bit helps, but if the alignment nodes keep running throughout the job, constantly picking up new tasks, then they should only have to load once at the start of a run and then go for at least several hours at least, yes?

**Comment by ababaian** [comment]
I'm just going to be documenting the optimizations I can think of as they come up.

But consider this also is runtime * 9 Gb * M (~100) instances of EBS which can be trimmed off.

**Comment by ababaian** [comment]
Axe this due to `musl`
