### ISSUE TITLE
Improve the HTML status page

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#10]
Right now the HTML status page is a giant static table.  It's better than querying raw SQL, but could be much better.  Here are some things that come to mind:

- [ ] Use less precise start time, and a time delta.  Example "2020-03-38 4:58:03.2 +328.628624s" (Sub second precision is nice for finding things in the logs)
- [ ] Group blocks by accessions, with [accordian boxes](https://mdbootstrap.com/snippets/jquery/cam/979615).
- [ ] Show the alignment progress (number of blocks finished/error/total) as part of each accession line.
- [ ] Colour-code things (green for success, red for failure? Or maybe purple/yellow for our colourblind friends?)

This isn't a definitive list, just some things I would love to have.  If you have other ideas for how to display what's going on, I'd love to see them! :D

**Comment by ababaian** [comment]
- [ ] As a side/addition, integrate a separate tab or window to include [Alignment Analysis](https://github.com/ababaian/serratus/tree/master/runs/analyze_run) graphs (Rmd currently) which are updated in real time. I think that can be done with a shiny app.

**Comment by ababaian** [comment]
- [ ] For each SRA, have a click to expand to show block status, with a counter of how many blocks in that accession are complete/generated . That is to interleave the data but hide the block data by default.
- [ ] A 'click to force restart' button that will send a curl command to the scheduler. We can then implement it to re-try an accession, you can leave the CURL command blank for now

**Comment by ababaian** [comment]
I think we can safely retire the HTML status page from further development as we have migrated to `postgres` to manage the data.

**Comment by jefftaylor42** [comment]
It still works!

Maybe our data volume has far exceeded its capacity though...

Manually poking the database is definitely a hack, we should not forget ..
