### ISSUE TITLE
Read QC before assembly

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#102]
From Graham Ruby author of the PRICE assembler:

[I highly recommend using] "PriceSeqFilter": PRICE Documentation: Independent Quality Filter.  Truth be told, many of the citations I get for PRICE are actually just for the use of this tool: even when the assembler isn't needed, filtering the reads like this is still useful for many genomics projects.  I'll recommend settings that Joe's lab has used after I left: “-rnf 90” and “-rqf 85 0.98” [ref. Illuminating uveitis: metagenomic deep sequencing identifies common and rare pathogens]"

Links:

[http://derisilab.ucsf.edu/software/price/](http://derisilab.ucsf.edu/software/price/)

[http://derisilab.ucsf.edu/software/price/PriceDocumentation140408/userManual.html](http://derisilab.ucsf.edu/software/price/PriceDocumentation140408/userManual.html)

Suggest assembly protocol developers try this, post feedback / results / other QC ideas under this issue.

**Comment by asl** [comment]
Few notes:
  - Certainly perform polyA trimming
  - Some light quality trimming would work as well (need to be careful on low-covered datasets as heavy trimming may create coverage gaps)

bbduk (from bbmap package) is quite nice, it has all necessary options and knows, multi-threaded and used by JGI. Could be used for masking / removing host bits as well.

Something like:
```
bbduk.sh trimpolya=15 qtrim=rl trimq=10 in=<left> in2=<right> out=<out-left> out2=<out-right> threads=<N>
```

would certainly work.

**Comment by asl** [comment]
Here is the set of JGI protocols: https://www.protocols.io/view/illumina-fastq-filtering-gydbxs6

**Comment by ababaian** [comment]
Closed by [Assembly Pipeline](https://gitlab.pasteur.fr/rchikhi_pasteur/serratus-batch-assembly)
