### ISSUE TITLE
README feedback

### ISSUE THREAD

**Issue by lisancao** [ababaian/serratus#118]
This readme is incredibly well documented in terms of what Serratus actually is and how it works, along with how to get it running locally. Well done. 

it is missing your contributors list though, due to the length of the list you may consider linking to a separate doc for this purpose, or putting a general "Thank you to our amazing contributors", or emphasizing that Serratus is an effort of people all over the globe from many different backgrounds.

**Comment by victorlin** [comment]
Hey @lisancao thanks for the feedback. Editing the README is something I'll be doing in the near future as we're moving to [wiki pages](https://github.com/ababaian/serratus/wiki). I'll add a blurb to address this.

**Comment by ababaian** [comment]
closed by #159
