### ISSUE TITLE
`fastq-dump` ignore technical

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#133]
See: [This page on fastq-dump](https://edwards.sdsu.edu/research/fastq-dump/)

**Problem:** Some libraries have technical reads such as bar-code index or other non-biological information. 

**Solution:** Add the `--skip-technical` option to fastq-dump such that these reads can be excluded.

This [chicken](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11616465) library is an example of a ilbrary with technical reads.

**Comment by taltman** [comment]
Note that in the case above, using --skip-technical will generate two files if splitting reads into files:
<id>_3.fastq 
<id>_4.fastq
If your pipeline is assuming that the files will be called <id>_1.fastq and <id>_2.fastq, you will need to check for this, and rename the files.

**Comment by ababaian** [comment]
```

**Comment by ababaian** [comment]
The `--split-e` only deals in biological reads to begin with. So inadvertently avoided this mistake. Looks like that spatial transcriptome library was just a particular case where the reads were mis-annotated, SRR11616465.
 
```
     --split-e                     3-way splitting for mate-pairs. For each
                                     spot, if there are two biological reads
                                     satisfying filter conditions, the first
                                     is placed in the `*_1.fastq` file, and
                                     the second is placed in the `*_2.fastq`
                                     file. If there is only one biological
                                     read satisfying the filter conditions,
                                     it is placed in the `*.fastq` file.All
                                     other reads in the spot are ignored.
```
