### ISSUE TITLE
`BLAST` containers

### ISSUE THREAD

**Issue by mathemage** [ababaian/serratus#14]
Research available `BLAST` containers and time the efficiency of each implementation.

_Originally posted by @ababaian  in 
https://github.com/ababaian/serratus/issues/5#issue-589616145_

**Comment by ababaian** [comment]
I'm currently implementing `magic-blast` in a container to benchmark against `bowtie2` alignment speed on CoV sequences.

**Comment by ababaian** [comment]
`magicblast` is now available using the `-a` flag to select either `-a bowtie2` or `-a magicblast`. Implementation is 'naive, index build if it's not available has not been implemented yet.
