### ISSUE TITLE
How to add images to wiki/img

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#141]
@victorlin or anyone else can you please explain how to upload images to wiki/img? Can this be done without having to issue a PR? Thanks!

**Comment by victorlin** [comment]
Yes, I will add a wiki page with steps.

You will have to clone the wiki (it is also a git repo) and commit/push the files to the master branch. It should work if you have push access to the serratus repo.

**Comment by rcedgar** [comment]
Great, thanks. I think this means that updates wiki text are immediately public, but any linked images will not be visible until a PR request is approved, did I get that right?

**Comment by ababaian** [comment]
PR requests are only to protect `master` of the main repository, it will not effect the wiki

**Comment by rcedgar** [comment]
I don't understand. What branch is the wiki on if not master? Are you saying the wiki directory does not have the same protections as the other directories so I can push without a PR, which I cannot do for src, notebook etc.?

**Comment by victorlin** [comment]
We are talking about two repositories here:

1. `https://github.com/ababaian/serratus.git`
2. `https://github.com/ababaian/serratus.wiki.git`

The files in each repository are independent. PRs submitted through GitHub are only valid for the `serratus` repository. The `serratus.wiki` repository contains its own files, and modifying pages is made easy through the GitHub website. You'll have to clone and edit this repository locally to add images.

---

Here is a wiki page that should help: [Wiki Management](https://github.com/ababaian/serratus/wiki/Wiki-Management)

**Comment by rcedgar** [comment]
Oh I see, thanks! Suggest linking to Wiki Management & contributing.md if not already done (I missed if so). Closing issue.
