### ISSUE TITLE
Daily web site graphics

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#148]
@Gherman @Artem Babaian How about this idea? Generate daily graphical stats showing the progress of the search. Number of genomes, number of host species (with pictures?), how many amplicon genomes we have found and expect to extend to full-length, geography on a map etc. Whatever is easy to get out of Tantalus, probably very low priority but if easy to do would be nice to post something on serratus.io which quickly shows what we've accomplished, might help attract collaborators.

**Comment by ababaian** [comment]
@victorlin We're starting to get stats out of R files. What would it take to get some of these summary statistics online in a fairly easy way to update?

**Comment by victorlin** [comment]
I think we’ll have to hop on a call and hash out some details here:

1. where/how the data is generated
2. figures (line chart, map, etc.)

@lohrd might need some help on implementing this in the Vue front-end

**Comment by rcedgar** [comment]
This should be very simple, or not worth the effort. I was thinking Tantalus could generate one (or a few) figures in .jpg by running a job once per day. These could be posted to s3 and copied over for the web site, also automatically. Can something like that be implemented easily?

**Comment by ababaian** [comment]
Yeah that's the "big picture" with Tantalus, I've been trying to get these pieces together but it looks like all the components are now ready. How would be a call later today be @victorlin + @lohrd

**Comment by victorlin** [comment]
I’m a bit tied up today, how about sometime after 2:30 PT early this week?

**Comment by ababaian** [comment]
sure, all good for me

**Comment by lohrd** [comment]
Sorry just seeing this now, will be free for a call at any time tomorrow, just let me know!

________________________________

**Comment by rcedgar** [comment]
Tantalus daily report I'd like to see if not too hard is the top "money hits", i.e. high-scoring, low-identity Covs. Could be posted anywhere convenient, S3 whatever, doesn't have to be the web site.

**Comment by rcedgar** [comment]
Closing issue, not worth doing now.
