### ISSUE TITLE
Software implementations of `Bloom Filters`

### ISSUE THREAD

**Issue by mathemage** [ababaian/serratus#15]
Find software implementations of `Bloom Filters` that we can use to stream data through and select possible CoV Reads

_Originally posted by @ababaian  in 
https://github.com/ababaian/serratus/issues/5#issue-589616145_

- [ ] Curate a list of available bloom filter software. Include licenses, is it command line, language it's written in, website, academic paper reference if available.
- [ ] Build each software package in a container and test how long it takes to process a benchmark set of RNA-sequencing libraries against a small test filter.
- [ ] (If needed, we can alter the program to accept RNA-sequencing reads (in `fastq`) format from a data-pipe.)

_Originally posted by @ababaian  in 
https://github.com/ababaian/serratus/issues/15#issuecomment-605519889_

**Comment by mathemage** [comment]
@jefftaylor42 @ababaian 
1. What exactly do you mean by software implementation? A library? A standalone program? An AWS functionality?
2. In which programming language should it be?

**Comment by ababaian** [comment]
The implementation may be different for different software. One example is [BIGSI](http://www.bigsi.io/) although it's kind of backwards to what we're hoping to do. In this case there already is a container available so we would only have to modify it slightly to accept data from a stream and/or incorporate it into the `serratus-dl` containers. I honestly am not well versed on all the options available and it needs to be researched and then we need to compare the speed/efficiency of each Bloom Filter to ensure it doesn't lag the whole pipeline.

**Comment by mathemage** [comment]
@jefftaylor42 @ababaian I suggest adding tag `Bioinformatics` to this issue.

**Comment by ababaian** [comment]
@emreerhan we could use your sage advice on this issue when you get a chance.

**Comment by emreerhan** [comment]
My first thought is the bloom filter library developed by the Birol lab and used in BioBloom tools: https://github.com/bcgsc/biobloom

License: GPL3 licence (free for academic use; not sure if this is an issue)
Language: C++
doi: 10.1093/bioinformatics/btu558

**Comment by emreerhan** [comment]
BIGSI has an incredibly easy to use bloom filter class. https://github.com/Phelimb/BIGSI/blob/master/bigsi/bloom/bloomfilter.py

License: MIT
Language: Python
doi: http://dx.doi.org/10.1038/s41587-018-0010-1

**Comment by ababaian** [comment]
We'll tentatively shut down Bloom Filters until there is a good reason to re-visit them.
