### ISSUE TITLE
`cov4` Update notes

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#166]
Additional notes for updating to `cov4` when that happens:

### Blacklisting Regions

`JB181528.1:3,840-4,780` : Cloning vector fragment, partially masked, extend to 4780 or end of sequence.

`NC_003391.1:9,224-9,701` : Camelpox similar region to `TMBIM4` gene

`NC_001653.2:686-725` : Deltavirus, small region with cryptic similarity to synthetic plasmids

**Comment by rcedgar** [comment]
KY419108 "Porcine hemagglutinating encephalomyelitis virus strain PHEV CoV USA-15TOSU24992, complete genome" is not a complete genome (~800nt, no ORFs).

JB181528.1 probably non-Cov, see SRR1055720 (good coverage of JB181528.1 but not mprot).
