### ISSUE TITLE
Genbank Contributors List

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#171]
As we're preparing the the pipeline for automated GenBank submission we'll need to list the project contributors as the files go online. Our current list is below taken from the `CONTRIBUTORS.md` file. This will be prepared into a `.sbt` template file from GenBank.

My suggestion is we randomize the name-order per each sequence-submission, this way we all average out as contributors.

### Serratus Contributors
- Artem Babaian
- Robert C. Edgar
- Jeff Taylor
- Kyl Wellman
- Rayan Chikhi
- Anton Korobeynikov
- Ryan J. McLaughlin
- Dmitry Meleshko
- Tomer Altman
- Steven J. Hallam
- Victor Lin
- Dan Lohr
- Gherman Novakovsky
- Nicole Pereyaslavsky

**Comment by rchikhi** [comment]
Counter-point: a random order might confuse external observers / introduce noise to metadata?
