### ISSUE TITLE
Determine if contig terminates at 3' end of genome

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#175]
We need to know if an assembly ends at the 3' end of the genome. The genome is expected to end with poly-A, but apparently this is trimmed by the assembler as a QC step.

Open problem: how to determine if a contig ends at the 3' end of the genome.

**Comment by taltman** [comment]
I think this can be handled by VADR, I'll just need to figure out the correct output file to mine for this info.

**Comment by rcedgar** [comment]
Solved as in #176, use RFAM HMMs or blastn to UTRs.
