### ISSUE TITLE
Write a script to copy outputs

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#18]
I always find myself typing `echo yes | terraform destroy`, then realizing I haven't saved something important and frantically trying to save everything as terraform destroys it all.

It would be nice to have a script that:

- Downloads and saves the .bam, .bai, and flagstat outputs from S3
- Downloads and saves a dump of the scheduler state
- Downloads and saves a dump of the cloudwatch logs
- ...and more.

Which we can run, and then do `terraform destroy` with confidence that we haven't forgotten something.

**Comment by ababaian** [comment]
you should adjust your terraform vars files to move the final output to another permanent S3 bucket on us-east-1. Fixes problem 1

**Comment by ababaian** [comment]
This is integrated into standard workflow now.
