### ISSUE TITLE
Report of July 8th assemblies (1.3k datasets)

### ISSUE THREAD

**Issue by rchikhi** [ababaian/serratus#185]
- 1.9k datasets were sent to me by Artem
- 1378 of those were not previously assembled ([list](https://gitlab.pasteur.fr/rchikhi_pasteur/serratus-batch-assembly/-/blob/master/lists/CoV_id95-60_reads100p_score30p.unique.txt))
- all were Batch assembled today except 18 couldn't be downloaded
- 1362 out of 1378 : coronaSPAdes reported a `bgc_statistics.txt` file (possibly empty)
- 696 out of 1378 had a non-empty  `bgc_statistics.txt` file
- 768 out of 1378 had a `checkv_filtered.fa` file (possibly empty) -> coronaSPAdes completed successfully & CheckV was run 
- regarding the others (1378-768=610): didn't investigate in details, but often, coronaSPAdes crashed due to > 30 GB memory
- only 14 (!) of `checkv_filtered.fa` files were non-empty, the 754 others were empty
- but the word 'CoV' occurs in 72 `bgc_statistics.txt` files !
- Among those 72, 16 have >= 2 CoV BGC candidates (those with 1 CoV BGC candidate are likely false positives)

Breakdown of the 768 assemblies:
![image](https://user-images.githubusercontent.com/1218301/86970961-9c3d9180-c170-11ea-8c53-4e31c78ccb17.png)

Recall that catC is `total_length > 5000 and total_length <= 25000`, catE is `nb_contigs == 0`, and everything else is catD.

The lucky 14 non-empty `checkv_filtered.fa`, along with BLASTx hits to NR.

|     | Accession   |   NbContigs |   TotalLength | Category   | Organism                        | BestRef        |   RefCovBases |   LongestHit |     IDY |
|----:|:------------|------------:|--------------:|:-----------|:--------------------------------|:---------------|--------------:|-------------:|--------:|
|  66 | ERR3994141  |           1 |         14188 | C          | Syngnathus typhle               | QEG08237.1     |          2528 |         2274 | 47.428  |
| 318 | ERR3994142  |           1 |         10440 | C          | Syngnathus typhle               | QEG08237.1     |          2528 |         2274 | 47.428  |
| 743 | ERR3994143  |           1 |         10910 | C          | Syngnathus typhle               | QEG08237.1     |          2528 |         2274 | 47.428  |
| 575 | ERR3994223  |           1 |         19802 | C          | Syngnathus typhle               | QEG08237.1     |          2655 |         2274 | 42.05   |
| 654 | SRR1324965  |           1 |         16484 | C          | Hippocampus kuda                | QEG08237.1     |          2528 |         2285 | 47.604  |
| 114 | SRR2418623  |           1 |         17616 | C          | Microhyla fissipes              | YP_009824965.1 |          3281 |         2741 | 30.176  |
| 530 | SRR5997671  |           1 |          8273 | C          | Acanthemblemaria sp. CUR14058.G | QEG08237.1     |          2568 |         2285 | 52.781  |
| 500 | SRR7226349  |           1 |          5849 | C          | Silurus asotus                  | YP_009755895.1 |          2052 |         2122 | 31.81   |
|  42 | SRR8389821  |           1 |         14666 | C          | Chelonia mydas                  | YP_009755838.1 |          1303 |         1331 | 35.162  |
| 620 | SRR8389822  |           1 |         20715 | C          | Chelonia mydas                  | QII89046.1     |          3314 |         2739 | 31.3375 |
| 433 | SRR8389835  |           1 |         16097 | C          | Chelonia mydas                  | ATP66725.1     |          1846 |         1875 | 36.267  |
| 748 | SRR8389847  |           1 |         17948 | C          | Caretta caretta                 | QII89046.1     |          2440 |         2472 | 39.32   |
|  31 | SRR9211911  |           1 |         10208 | C          | Ambystoma mexicanum             | QEG08237.1     |          2544 |         2294 | 43.951  |
| 539 | SRR9211912  |           1 |          8178 | C          | Ambystoma mexicanum             | QEG08237.1     |          2530 |         2280 | 43.974  |

The additional 16 with 2+ BGC candidates CoVs, along with BLASTx hits to NR.

| BGC CoV candidates | Accession |  Organism |  BestRef        |   RefCovBases |   LongestHit |     IDY |
|--|----|----|--|----|----|--|
| 7 | [SRR8389793](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389793.coronaspades/SRR8389793.coronaspades.bgc_statistics.txt) | Caretta caretta |  BBC54860.1 | 88 | 89 | 38.20 | 
| 7 | [SRR8389791](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389791.coronaspades/SRR8389791.coronaspades.bgc_statistics.txt) | Caretta caretta |  QGX41950.1 | 199 | 205 | 31.71 | 
| 6 | [SRR8389832](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389832.coronaspades/SRR8389832.coronaspades.bgc_statistics.txt) | Caretta caretta |  QGX41950.1 | 231 | 237 | 32.07 | 
| 6 | [SRR8389823](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389823.coronaspades/SRR8389823.coronaspades.bgc_statistics.txt) | Chelonia mydas |  YP_009505583.1 | 1125 | 1177 | 32.03 | 
| 5 | [SRR8389837](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389837.coronaspades/SRR8389837.coronaspades.bgc_statistics.txt) | Chelonia mydas |  APZ73806.1 | 77 | 79 | 40.51 | 
| 5 | [SRR8389831](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389831.coronaspades/SRR8389831.coronaspades.bgc_statistics.txt) | Caretta caretta |  YP_008439219.1 | 97 | 98 | 38.78 | 
| 5 | [SRR8389794](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389794.coronaspades/SRR8389794.coronaspades.bgc_statistics.txt) | Caretta caretta |  AKQ98477.1 | 156 | 157 | 43.95 | 
| 5 | [ERR3994145](https://serratus-public.s3.amazonaws.com/assemblies/other/ERR3994145.coronaspades/ERR3994145.coronaspades.bgc_statistics.txt) | Syngnathus typhle |  QEG08237.1 | 152 | 153 | 38.56 | 
| 4 | [SRR8389849](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389849.coronaspades/SRR8389849.coronaspades.bgc_statistics.txt) | Caretta caretta |  YP_009755838.1 | 178 | 179 | 36.87 | 
| 4 | [SRR8389825](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8389825.coronaspades/SRR8389825.coronaspades.bgc_statistics.txt) | Chelonia mydas |  QJA42019.1 | 86 | 90 | 36.67 | 
| 4 | [SRR8181903](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR8181903.coronaspades/SRR8181903.coronaspades.bgc_statistics.txt) | Microhyla fissipes |  AWV67106.1 | 80 | 82 | 47.56 | 
| 4 | [ERR3994210](https://serratus-public.s3.amazonaws.com/assemblies/other/ERR3994210.coronaspades/ERR3994210.coronaspades.bgc_statistics.txt) | Syngnathus typhle |  QEG08237.1 | 82 | 83 | 61.45 | 
| 3 | [SRR6788810](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR6788810.coronaspades/SRR6788810.coronaspades.bgc_statistics.txt) | Ambystoma mexicanum |  AVM87573.1 | 107 | 109 | 46.79 | 
| 3 | [SRR5997814](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR5997814.coronaspades/SRR5997814.coronaspades.bgc_statistics.txt) | Percopsis omiscomaycus |  AHB63480.1 | 209 | 188 | 38.11 | 
| 2 | [SRR7061292](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR7061292.coronaspades/SRR7061292.coronaspades.bgc_statistics.txt) | Danio rerio |  XP_009291307.2 | 3118 | 511 | 64.49 | 
| 2 | [SRR2418554](https://serratus-public.s3.amazonaws.com/assemblies/other/SRR2418554.coronaspades/SRR2418554.coronaspades.bgc_statistics.txt) | Microhyla fissipes |  ADX59487.1 | 2646 | 2737 | 34.86 |

**Comment by rcedgar** [comment]
@rchikhi would be helpful to see most similar known genome  & %id and/or Serratax prediction, this tells us whether the assembly is high- or low-value target worth giving more attention to, e.g. co-assembly.

**Comment by rchikhi** [comment]
Sounds fair, will do that tomorrow

**Comment by rchikhi** [comment]
Actually, Serratax wasn't run on the extended 16 as only a subset of the contigs correspond to a CoV HMM hit, the rest of the contigs do not. Would you say it's fine to run Serratax on just the CoV-HMM-hit contig ?

**Comment by rcedgar** [comment]
Serratax supports multi-contig assemblies. It looks for a few known genes by ublast, then aligns & builds trees for each found gene on the fly. If a subset of genes is found, that's ok. If no genes are found, empty :-)

**Comment by rchikhi** [comment]
It is done for the lucky 14. The additional 16's will take extra time as blastx for the 14 contigs took 9 hours on a 16cores ec2.. weird?

**Comment by rchikhi** [comment]
I've updated the results with the additional 16 viruses extracts from bgc_statistics.txt.  Much shorter hits (~80 nt sometimes). Is this significant?

**Comment by rcedgar** [comment]
I don't understand which hits your talking about exactly, but viruses evolve very quickly. In Cov, aligning one genus to another is <~50% a.a. identity in short well-conserved regions in protein core, lower elsewhere; nt similarity is probably undetectable over most of the genome with blastn though I haven't looked at this carefully. Cov has proofreading; most other viruses evolve more quickly.

**Comment by rchikhi** [comment]
those hits were the longest BLASTx hits from contigs to NR database

**Comment by rcedgar** [comment]
If these are hits to well-conserved domains in pol with low E-value, this could be a very deeply diverged Cov. You should also look at where the genes are in the contig, Cov+Toro have well-conserved gene structure in ORF1ab. This needs a fair amount of manual review to make a call IMO.

**Comment by rchikhi** [comment]
fair enough, sounds like a good follow-up project if we have time a bit later than this week. I guess for now a couple other things are more down-to-earth urgent.

**Comment by rcedgar** [comment]
Agreed. Artem & I call this kind of thing HHF/LWIA = high-hanging fruit / land war in Asia, meaning time-consuming, low probability of success, do it later / never.

**Comment by rchikhi** [comment]
well Artem may also call it 'NEW GENUS!' :)

**Comment by rcedgar** [comment]
Better test than blastx for low-%id assemblies is to run those taxonomic HMMs per #195 and #196. If these have good alignments, then we can determine new species, new sub-genus or new genus according to "official" standards.

**Comment by ababaian** [comment]
Note to self: go back and look at these sequences next weekend. LWIA
