### ISSUE TITLE
Automatically spin down when finished

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#19]
This is an edge case, albeit a useful one, to the idea that our ASGs should grow and shrink dynamically.

Current behaviour: Optimize costs by manually setting `desired_size` to 0, when a step in the pipeline is finished.

Desired behaviour: The scheduler should detect this condition, and set the `desired_size` to 0 automatically.

Caveats: If we decide to add more SRA data afterwards, we'll have to manually reset the desired_size.

**Comment by mathemage** [comment]
@jefftaylor42 

1. What's ASG?
2. Is this AWS issue?
3. If implemented, how can you test/simulate this? 

Can you give more details, please?

**Comment by jefftaylor42** [comment]
Have you had any luck with #9?

**Comment by mathemage** [comment]
> Have you had any luck with #9?

Not yet, @jefftaylor42 . I'm looking into this in the development branch https://github.com/mathemage/serratus/tree/iss-9-instance-doesnt-signal-the-scheduler-when-shutting-down of my fork. 

As of now, trying to build the containers. 

Will keep you updated. Thanks!

**Comment by ababaian** [comment]
ASG scaling now is operational.
