### ISSUE TITLE
Designate assemblies as putative new species or new genus

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#195]
The [ICTV criteria for Cov taxonomy assignment](https://talk.ictvonline.org/ictv-reports/ictv_9th_report/positive-sense-rna-viruses-2011/w/posrna_viruses/222/coronaviridae
), are quoted below.

This gives us the official criteria for claiming a putative new species, sub-genus or genus. The master table should therefore include a.a. identities to the domains used for classification. I'm not clear exactly what "domain" means here (#195).

"Established and newly identified members of the family Coronaviridae are assigned to a subfamily and genus on the basis of rooted phylogeny and calculation of pair-wise evolutionary distances [_sic, this surely should be "a.a. identities from pair-wise alignments_"] for the following Coronaviridae-wide conserved domains in replicase polyprotein pp1ab: ADRP, nsp5 (3CLpro), nsp12 (RdRp), nsp13 (Hel), nsp14 (ExoN), nsp15 (NendoU) and nsp16 (O-MT). This procedure, developed by Lauber and Gorbalenya (in preparation), at present unambiguously identifies 20 distinct non-overlapping clusters (with the largest intra-cluster distance being smaller than the smallest inter-cluster distance): 17 coronaviruses, 2 toroviruses, 1 bafinivirus). Likewise, the higher-rank clusters corresponding to genus and subfamily levels are recognized.

Phylogenetic outliers assigned to the family Coronaviridae may be considered representatives of a **new genus** when they do not cluster with any of the current genera and **share less than 46% sequence identity in the aforementioned conserved replicase domains with any other established member of the family**.

Viruses that share more than **90% aa sequence identity in the conserved replicase domains are considered to belong to the same species**. This 90% identity threshold serves as the sole species demarcation criterion."

**Comment by taltman** [comment]
Please make it clear what I need to do for this issue, or please create a separate issue that is just for my part. As it stands, I don't know what to do, and it's freaking me out. :-)

**Comment by rcedgar** [comment]
@taltman -- Apologies for the out-freaking. I opened the issues as an "FYI/what shall we do about this?" to the team, you did your part with the PFAM alignments) -- thanks! Now I own this one.
