### ISSUE TITLE
Good ideas to implement

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#2]
- [x] Migrate over to `us-east-1` region for closer access to NIH AWS systems and not get dinged for cross-region I/O

**Comment by ababaian** [comment]
-[ ] `sratoolkit` works natively with AWS/GCP to access `SRA` archive files. Most data is stored in this format and requires `fastq-dump` from `sratoolkit` to start the pipeline. Some modern SRA entries already contain bam or fastq files, these would be faster to access via `fusera`. Add a "Try Fusera" to access fq files first then fall-back on sratoolkit fq dump which is the current default

**Comment by ababaian** [comment]
- [ ] From `SraRunInfo` table we know the size of the file in Mb. Can we dynamically/rapidly provision how much EBS space the EC2 instance has so that it's say 5 Gb + 3xSRA size. i.e. for a 2 Gb SRA it will have 5 Gb + 3x2 = 11 Gb. Then the next job is 100 Gb so we'll need 5 Gb + 3x100 = 305 Gb on EBS, then the next job is 200 Mb and we need ...

**Comment by ababaian** [comment]
- [ ] Switch `fastq-dump` to `fasterq-dump` which has parallel processing of the SRA files to speed up download. We need to have a measurement of what is the bottleneck, CPU cores or network speed. This will give us an idea of how to scale up downloading.

**Comment by jefftaylor42** [comment]
- [ ] Try to build bowtie2 on ARM, to take advantage of ~1/2 price A1 instances.

**Comment by ababaian** [comment]
- [ ] In `fastq-dump` or `fasterq-dump` allow the outputfile files `SRA_1.fastq, SRA_2.fastq, SRA_3.fastq` to be directly piped into `split` using named pipes. Something like `mkfifo $SRA{,_1,_2}.fastq; fastq-dump & split < $SRA_1.fastq`

**Comment by ababaian** [comment]
- [ ] Try to abstract away the entire `serratus-align` layer into AWS Lambda functions. See: [1](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html) [2](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).
