### ISSUE TITLE
S3 Tier1 Requests are 5x higher than expected

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#20]
S3 Tier1 requests include PUT/COPY/POST/LIST, and these are priced at $0.005 / 1000 requests.

### Expected behaviour:
 - 1 PUT / block in serratus-dl (for the fq-blocks)
 - 1 PUT / block in serratus-align (for the bam-blocks)
 - Several LISTs in serratus-merge, but not more than 10 / accession.

### Actual behaviour:
- Dataset with ~1600 blocks results in ~10,000 Tier1 requests, which represents ~22% of overall cost at the moment.

**Comment by ababaian** [comment]
I knew we're cheating the devil with accessing S3 'free'. As we titre up fq-block size I think it will also reduce PUT numbers.

**Comment by jefftaylor42** [comment]
That may improve it, but it's also not clear what part of the code these requests are coming from.  I put a count up above.  Maybe `aws s3` is using a really tiny blocksize.  I think I've seen it before in the past.  Put this bug here to remind myself.

**Comment by jefftaylor42** [comment]
Duplicate of #26
