### ISSUE TITLE
Genbank records missing PFAM annotations

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#203]
AB551247.1

AF201929.1

AF208066.1

AY394999.1

FJ647219.1

FJ647220.1

FJ647221.1

FJ647223.1

FJ647224.1

FJ647227.1

JF792616.1

JF792617.1

JX169867.1

KF793825.1

KM349743.1

MH687968.1

MH687972.1

MH687974.1

MN690611.1

NC_010646.1

NC_025217.1

NC_048217.1

**Comment by taltman** [comment]
I re-ran NC_025217.1 and AB551247.1. In both cases, the pfam sub-directory was there, with all of the expected files. Reassigning to @rchikhi to see if he can re-run these cases, and either confirm my observation, or reproduce the bug you are seeing.

**Comment by taltman** [comment]
Weird, I cannot un-assign myself...

**Comment by rchikhi** [comment]
I've re-run everything as part of https://github.com/ababaian/serratus/issues/204

**Comment by rcedgar** [comment]
These are missing PFAM annotations in the new run:

AY395000.1
HQ850618.1
KC008600.1
KM609205.1
KR265759.1
KR822424.1
KX219798.1
KX236009.1
KX236011.1
KX252780.1
KX302862.1
KY983586.1
MG021451.1
MG428702.1
MK071620.1
MN535737.1
MN692789.1
MN794188.1
MT263013.1
NC_034976
NC_046956

**Comment by rchikhi** [comment]
They're being re-run, batch job ID's:
```
Job ID is dcba8e8c-6b8a-4a3e-a0dd-238d6e968a02.
Job ID is 011470b1-9259-4318-9d57-5b3b1e58639f.
Job ID is 6190ead6-eb74-43e7-b2a9-98fd2480f0fb.
Job ID is 4972fc3f-094e-462d-8b95-c5aa5af7ba90.
Job ID is 82c17cc3-cf0d-409b-95e6-ea549e6a0f9a.
Job ID is fe767b96-8daa-49e3-af36-1de6a8fe0d67.
Job ID is 0d218354-24e2-4ac5-963b-9d72cb7fb18a.
Job ID is 8de165a2-dc1c-47ce-aa70-bc11015b93a2.
Job ID is f64b55aa-1192-4118-9793-4f0bf05fead1.
Job ID is ff40c090-f83e-4c00-a574-17d38537592d.
Job ID is 47b45eba-cab2-4424-9eaf-b59641378a7a.
Job ID is ba851051-0cb4-4a9f-b6c1-4c01a60b24ff.
Job ID is 94afcd0b-1be5-4efe-973d-40f9ec586ae2.
Job ID is 226f315b-abf6-4f31-81c2-6f41abbd8912.
Job ID is 3fd02763-822e-4392-b68e-6f66c4bb671e.
Job ID is 2c1cd613-be51-47b1-8ca2-23f1acb71754.
Job ID is 3dc6490f-b3c1-4dc9-b8f6-c25c8fb9dcb1.
Job ID is a1e78d43-1bd9-44f4-a245-a750b0c9eb5a.
Job ID is dfed72a6-de68-407c-a4d1-633b60617124.
Job ID is a5d3cc42-2b82-4596-9d3c-3ec18b7e67c6.
Job ID is dafe809b-bec3-4a65-8b61-1d63b69ea1d3.
```

**Comment by rchikhi** [comment]
Quick rundown of the first 5:
Job 1 (AY395000.1): `Use of uninitialized value $uapos in concatenation (.) or string at /vadr/vadr/v-annotate.pl line 3757.`
Job 2 (HQ850618.1) : seems that it completed successfully
Job 3 (KC008600): seems that it completed successfully
Job 4 (KM609205.1): seems that it completed successfully

**Comment by taltman** [comment]
@rcedgar I checked all of the rest of the accessions. they all have non-zero `pfam/alignments.fasta` files. I've updated the issue I created at the VADR repo regarding `AY395000.1`. I think you can proceed with your task. Reassigning to you to confirm that you have no blocker now.
