### ISSUE TITLE
DARTH: Uninitialized value error from VADR

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#205]
```
2020-07-16T15:13:40.662-07:00
	
# sequence file: /serratus-data/AY394999.1.fa
	
2020-07-16T15:13:40.662-07:00
	
# output directory: /serratus-data/AY394999.darth/AY394999
	
2020-07-16T15:13:40.662-07:00
	
# force directory overwrite: yes [-f]
	
2020-07-16T15:13:40.662-07:00
	
# .cm, .minfo, blastn .fa files in $VADRMODELDIR start with key <s>, not 'vadr': corona [--mkey]
	
2020-07-16T15:13:40.662-07:00
	
# model files are in directory <s>, not in $VADRMODELDIR: /darth/vadr-models-corona-1.1-1 [--mdir]
	
2020-07-16T15:13:40.662-07:00
	
# set max allowed memory for cmalign to <n> Mb: 64000 [--mxsize]
	
2020-07-16T15:13:40.662-07:00
	
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	
2020-07-16T15:13:53.225-07:00
	
# Validating input ... done. [ 12.6 seconds]
	
2020-07-16T15:17:51.213-07:00
	
# Classifying sequences (1 seq) ... done. [ 238.0 seconds]
	
2020-07-16T15:18:40.031-07:00
	
# Determining sequence coverage (NC_004718: 1 seq) ... done. [ 48.8 seconds]
	
2020-07-16T15:21:34.850-07:00
	
# Aligning sequences (NC_004718: 1 seq) ... done. [ 174.8 seconds]
	
2020-07-16T15:21:34.973-07:00
	
Use of uninitialized value $uapos in concatenation (.) or string at /vadr/vadr/v-annotate.pl line 3757.
```

**Comment by taltman** [comment]
Confirmed this bug. Reported upstream to Eric at NCBI:
https://github.com/nawrockie/vadr/issues/21

**Comment by rcedgar** [comment]
@tomer this bug is independent of the PFAM annotations, right? Is it possible to run the PFAM alignments on the GB entries that crashed outside of VADR while we're waiting for the bug to be resolved?

**Comment by taltman** [comment]
It is not independent, as the Pfam annotations are currently used to identify the maturation proteins on ORF 1ab, and the gene-calling of ORF 1ab comes from VADR. 

The first thing I'd like to see is for @rchikhi to re-run these few samples, and see if that clears up some of the failed runs. I can then look at the output from that second run of each sample, to see what the issue is.

**Comment by taltman** [comment]
As I suspected, merely re-running them seemed to clear up ~96% of the issues. The two accessions that caused that obscure VADR crash have been reported up-stream to Eric.

**Comment by taltman** [comment]
Thanks @rchikhi for re-running. @rcedgar , please leave this open as a reminder on my part to follow up with Eric.

**Comment by taltman** [comment]
FYI, I filed this bug in the VADR repo, and Eric responded that he's currently working on a fix:

https://github.com/nawrockie/vadr/issues/21

**Comment by rchikhi** [comment]
looks like it's been fixed https://github.com/nawrockie/vadr/issues/21#issuecomment-661279793

**Comment by taltman** [comment]
Yep, he provided me with a work-around for now, and a proper fix will go out in the next VADR release, which will be a few weeks from now. I'll incorporate it into the updated version of DARTH that I'll send to you this evening.

**Comment by taltman** [comment]
Confirmed that my implementation of the work-around works for the example above. Closing!
