### ISSUE TITLE
Additional PFAM alignments

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#206]
1. I need PFAM alignments for these fragments for OTU construction: [cov5_fragment_final.id99.fa](https://serratus-public.s3.amazonaws.com/seq/cov5/cov5_fragment_final.id99.fa)

2. I also need PFAM alignments for the missing GB complete genomes due to the VADR bug (#203).

@taltman @rchikhi would it be possible to get these done more quickly & easily by running PFAM on the ORFs instead of waiting for a VADR fix? You could use any cli ORF-finder, e.g. [EMBOSS getorf](http://emboss.sourceforge.net/apps/cvs/emboss/apps/getorf.html) and run PFAM on those.

**Comment by taltman** [comment]
Sure, I can run then this weekend.

On July 17, 2020 1:11:18 PM PDT, Robert Edgar <notifications@github.com> wrote:
>1. I need PFAM alignments for these fragments for OTU construction:
>[cov5_fragment_final.id99.fa](https://serratus-public.s3.amazonaws.com/seq/cov5/cov5_fragment_final.id99.fa)
>
>2. I also need PFAM alignments for the missing GB complete genomes due
>to the VADR bug (#203).
>
>@taltman @rchikhi would it be possible to get these done more quickly &
>easily by running PFAM on the ORFs instead of waiting for a VADR fix?
>You could use any cli ORF-finder, e.g. [EMBOSS
>getorf](http://emboss.sourceforge.net/apps/cvs/emboss/apps/getorf.html)
>and run PFAM on those.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ababaian/serratus/issues/206

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rchikhi** [comment]
I'm stealing those from your plate @taltman !

**Comment by rchikhi** [comment]
Results for cov5_fragment_final.id99 are coming to https://s3.console.aws.amazon.com/s3/buckets/serratus-public/seq/cov5/annotations/?region=us-east-1&tab=overview and will be completed in ~30mins

**Comment by taltman** [comment]
@rchikhi Can you briefly describe how you did this? I don't recommend most ORF callers for this application due to frame shifts. FragGeneScan is the only one that I am aware of that handles this.

**Comment by rchikhi** [comment]
I ran Darth :) on each of these fragments.

**Comment by rcedgar** [comment]
Any generic ORF caller is fine, there are no frameshifts within the PFAM domains. E.g. I use getorf in serratax. Note that PFAM domains are shorter than the full-length gene / ORF / CDS / cleaved product (any of these).

**Comment by rcedgar** [comment]
Closed, issue superseded by #211.
