### ISSUE TITLE
Run annotation pipeline on 99% nt OTUs

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#211]
We need annotations for the updated nt OTUs, FASTA here:

[https://serratus-public.s3.amazonaws.com/seq/cov5/nt_otus.id99.fa](https://serratus-public.s3.amazonaws.com/seq/cov5/nt_otus.id99.fa)

**Comment by rchikhi** [comment]
on it

**Comment by rchikhi** [comment]
they're all done, in `s3://serratus-public/seq/cov5/annotations.nt_otus.id99/`
good luck with fig1!
