### ISSUE TITLE
Align poly-A tail reads against assembly to identify putative 3' of genome

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#222]
If we can clearly identify the start and the end of a CoV genome, we could be more confident in labeling a given assembly as complete or partial, and also for helping to disentangle very complicated CoV assembly graphs. At first, we thought that we could use 5' & 3' UTR models, but these regions lacked adequate conservation. While the rest of the 5' end is full of well-defined and predictable protein domains, the 3' end of the genome has a more complicated arrangement of smaller CDS, with varying order.

@asl and I discussed the following procedure:

1. Identify reads with a poly-A tail
2. Trim off the poly-A tail portion of the read to avoid non-specific alignment
3. Align the reads against the assembly

When clusters of these reads all align to the end of the same contig in an assembly, we can infer that this is the poly-A tail region. This could tell us where the 3' end of the genome is.

@rcedgar @rchikhi @ababaian, clue me in on the biology that I'm butchering here.

**Comment by taltman** [comment]
... could this also identify the 3' end of alternative viral transcripts?

**Comment by rchikhi** [comment]
note: all the reads I downloaded were immediately polyA-trimmed by fastp for assembly

**Comment by taltman** [comment]
Going forward, we could notate those reads' IDs before trimming. And then retain the IDs for doing this sort of analysis. And we could probably do this for the handful of tough cases where we need some help disentangling the assembly graph.
