### ISSUE TITLE
Assemblies were updated (7/28) due to two bugs

### ISSUE THREAD

**Issue by rchikhi** [ababaian/serratus#230]
Due to two parsing bugs, the list of assemblies along with the master table was updated today. 

As usual, latest assemblies are in `s3://serratus-rayan/master_table_assemblies/`
And the new master table is in: `s3://serratus-rayan/sra_master_table.csv`

Damage report: 
* 72 assemblies (0.6% of the master table) are updated
* 558 new accessions have been added to the master table. 

This brings the number of assemblies in master table from 11,125 to **11,683**.

Explanations:
* The 72 updated assemblies were from previous runs (e.g. an early STAT run) and not properly updated with latest coronaspades run. This was due to a bug in `pyfasta` package which created a cache file of old assemblies, without detecting and refreshing that cache when newer assemblies were present.
 * The 558 new accessions are due to me not using an up-to-date list of accessions when computing the master table.

@ababaian  @rcedgar, a decision should be made on whether to rerun all downstream analysis of assemblies based on these changes.

**Comment by rchikhi** [comment]
Summary of the 72 updated assemblies:

accession | #contigs (before) | #contigs (after) | Total length (before) | Total length (after) | * = wasn't part of the rescaffolding
-|-|-|-|-|-
ERR1301563 | 7 | 7 | 3783 | 22244 |
ERR326319 | 4 | 4 | 2060 | 3185 |
SRR11907539 | 13 | 13 | 8944 | 9154 |
SRR1287029 | 6 | 6 | 2969 | 4751 |
SRR3401559 | 4 | 4 | 48898 | 56750 |
SRR5679269 | 1 | 1 | 313 | 835 | *
SRR5912631 | 15 | 15 | 5261 | 5065 | *
SRR5912667 | 25 | 25 | 13402 | 13823 | *
SRR5947156 | 1 | 1 | 230 | 340 | *
SRR6713719 | 12 | 12 | 17898 | 3636 | *
SRR6713783 | 25 | 25 | 27373 | 10776 | *
SRR6713821 | 19 | 19 | 7829 | 8232 | *
SRR6713884 | 2 | 2 | 594 | 1064 | *
SRR6713899 | 17 | 17 | 5893 | 21919 | *
SRR6962695 | 14 | 14 | 5330 | 5211 |
SRR6994277 | 1 | 1 | 403 | 719 | *
SRR7236345 | 10 | 10 | 5775 | 29910 | *
SRR7239366 | 3 | 3 | 771 | 839 |
SRR7239370 | 3 | 3 | 782 | 969 |
SRR7267810 | 2 | 2 | 510 | 2043 |
SRR7267813 | 4 | 4 | 6716 | 1139 |
SRR7267814 | 4 | 4 | 1298 | 2077 |
SRR7287177 | 17 | 17 | 33715 | 10992 | *
SRR7293002 | 5 | 5 | 2616 | 2538 |
SRR7310195 | 3 | 3 | 1165 | 3712 | *
SRR7694367 | 2 | 2 | 1107 | 856 | *
SRR7694421 | 2 | 2 | 993 | 1006 | *
SRR7734135 | 3 | 3 | 1133 | 1105 |
SRR7811493 | 2 | 2 | 477 | 2877 | *
SRR7880365 | 1 | 1 | 472 | 394 | *
SRR7963139 | 2 | 2 | 684 | 799 | *
SRR7989585 | 1 | 1 | 326 | 1805 | *
SRR8082048 | 8 | 8 | 2862 | 2594 |
SRR8100122 | 1 | 1 | 796 | 369 | *
SRR8181915 | 3 | 3 | 1156 | 966 | *
SRR8381829 | 14 | 14 | 25001 | 25098 | *
SRR8381871 | 8 | 8 | 18887 | 18365 | *
SRR8570622 | 2 | 2 | 7085 | 924 |
SRR8663627 | 4 | 4 | 1192 | 2048 | *
SRR8791652 | 7 | 7 | 1771 | 1777 | *
SRR8835215 | 5 | 5 | 1710 | 4603 | *
SRR8835218 | 6 | 6 | 1967 | 8764 | *
SRR8835219 | 3 | 3 | 1084 | 2713 | *
SRR8857868 | 1 | 1 | 239 | 246 | *
SRR9017114 | 8 | 8 | 4342 | 375527 | *
SRR9112936 | 1 | 1 | 289 | 227 | *
SRR9214145 | 4 | 4 | 1224 | 9425 |
SRR9420820 | 1 | 3 | 31071 | 31782 | *
SRR9420853 | 1 | 1 | 31353 | 31324 | *
SRR9420864 | 1 | 2 | 31326 | 31822 | *
SRR9420897 | 1 | 1 | 31074 | 31072 | *
SRR9425850 | 1 | 1 | 29268 | 29214 | *
SRR9425861 | 2 | 2 | 49198 | 24778 | *
SRR9425885 | 1 | 2 | 29271 | 25634 | *
SRR9425896 | 1 | 2 | 29346 | 29738 | *
SRR9425918 | 1 | 2 | 29370 | 29545 | *
SRR9426065 | 1 | 2 | 27982 | 25378 | *
SRR9426084 | 1 | 2 | 29275 | 29380 | *
SRR9426158 | 1 | 2 | 29329 | 29468 | *
SRR9426180 | 1 | 3 | 29341 | 23420 | *
SRR9426202 | 1 | 2 | 29354 | 23801 | *
SRR9426213 | 1 | 1 | 29320 | 29318 | *
SRR9426245 | 1 | 1 | 29301 | 25529 | *
SRR9426803 | 1 | 1 | 31486 | 31295 | *
SRR9429885 | 1 | 2 | 31351 | 31500 | *
SRR9429886 | 1 | 3 | 31531 | 31959 | *
SRR9429889 | 1 | 2 | 31337 | 31484 | *
SRR9430147 | 3 | 3 | 54274 | 20836 |
SRR9432695 | 1 | 2 | 29695 | 18302 | *
SRR9433383 | 1 | 2 | 31187 | 26998 | *
SRR9433387 | 1 | 1 | 31328 | 31327 | *
SRR9617592 | 1 | 2 | 28017 | 56034 | *

**Comment by rchikhi** [comment]
And the complete list of the 72+558 accessions: `s3://serratus-public/assemblies/analysis/pyfasta.bug.0728.txt`

**Comment by ababaian** [comment]
are any of these novel OTU?

**Comment by rcedgar** [comment]
Don't know, waiting on @rchikhi to send RdRp's

**Comment by rchikhi** [comment]
Ahh, for the 558 new accessions, I now realize why they weren't included in the first place: I had excluded all accessions that failed to be assembled with the latest coronaspades version. Most likely they were failed Batch runs with latest coronaspades, which didn't fail in an earlier Batch run. So in a way, it is good to not include them in the paper. I'll revert the master table so that it only contains accessions assembled using the same coronaspades version.

**Comment by rchikhi** [comment]
Yet, to see whether we missed anything important, I sent the RdRP's to @rcedgar earlier today : https://serratus-public.s3.amazonaws.com/assemblies/analysis/rdrp.0728.new_accessions.fa

**Comment by rchikhi** [comment]
Closing as the 558 missing runs will simply be re-run later.
