### ISSUE TITLE
Explore Nextflow as an Alternative Architecture

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#24]
[Nextflow](https://github.com/nextflow-io/nextflow) is a system for defining and running Genomics pipelines.  It supports a variety of Grid Computing systems, as well as running directly on EC2.

I skimmed the docs to see how it handles [file splitting](http://nextflow-io.github.io/patterns/index.html#_process_per_file_chunk):

> By default chunks are kept in memory. When splitting big files specify the parameter file: true to save the chunks into files. See the documentation for details.

There's no mention of buckets or any other mechanism for splitting work across instances.  That means one of two things:
 - It's a good fit, but doesn't support the feature set we need.  We should consider contributing to that project to benefit the scientific community as a whole.
 - OR it's not a good fit, it's designed for smaller jobs than what we're doing.

I'm a huge fan of the pipeline description language—imagine being able to plug their example code into a system like Serratus and have it magically go to extreme scale—this would have huge implications both inside and outside of bioinformatics.  It would probably be worth it to spend a day or two implementing a pipeline with their system, just to see if it's all we're imagining it to be.

**Comment by Zethson** [comment]
I'm an nf-core developer and can answer most of your questions I hope. Nextflow scales extremely well on machines with lots of cores, since it can easily parallelize the data flow without any additional developer effort. The channel architecture takes care of that.

A colleague of mine actually implemented a SRA Downloader pipeline just recently.

**Comment by ababaian** [comment]
I'm super interested in having a chat with you if you have time. You'll have to excuse my ignorance about NextFlow but right now it looks like a good fit. Shoot me an email and we can arrange (ababaian AT bccrc DOT ca)

**Comment by jefftaylor42** [comment]
Oh awesome!  We're not looking at it straight away since it's a big shift in direction, but I'll definitely ask you lots of questions later! :)

Right now we're actually using S3 for our pipelines.  It seems to be a lot faster and cheaper than using EFS for example.  I didn't dig deep but I only found stuff about using files for pipelines (quoted above).  Do you know off hand if NF supports S3 for its channels?

Are there lots of developers doing scale-out (many instance) problems using Nextflow?

Thanks for introducing yourself.  We'll definitely be taking advantage of your expertise in a short while. :)

**Comment by Zethson** [comment]
@ababaian  Sure, will do!

@jefftaylor42 About S3: https://www.nextflow.io/docs/latest/amazons3.html

> Are there lots of developers doing scale-out (many instance) problems using Nextflow?

Yes. Even though most people have access to huge clusters (Slurm etc) at their institution, some are also running it successfully on AWS, Google Cloud, [...].
The [nf-core](https://nf-co.re/) template already has AWS preconfigured for an easy start up.

And a sidenote: 

> Nextflow is a system for defining and running Genomics pipelines

Nextflow is used for more than just Genomics. A friend of mine implemented an image analysis pipeline and I myself am mostly contributing with proteomics pipelines.

I suggest that you explore nf-core. If your pipeline fills a niche, nf-core is always happy to include new pipelines. See the website for benefits for all parties.

Cheers.

**Comment by ababaian** [comment]
We will return to this once we have 'settled' on a working pipeline. Closing for now.
