### ISSUE TITLE
Please run SRA SRR11085797

### ISSUE THREAD

**Issue by bioscienceresearch** [ababaian/serratus#243]
NCBI SRA SRR11085797 contains sequence reads for RaTG13, the closest ancestor to SARS-CoV-2. 

https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11085797

As such it is an impotant CoV to study

**Comment by ababaian** [comment]
Hello, that sample has already been run: https://serratus.io/explorer?run=SRR11085797#result

You can visualize the data directly in [JBrowse](https://serratus.io/jbrowse?bam=SRR11085797&loc=MN996532.1) built into the website. Looks like it has RaTG13 as the online [meta-data](https://www.ncbi.nlm.nih.gov/sra/?term=SRX7724752) suggests.

**Comment by ababaian** [comment]
If you have a list of samples to process please keep it to one issue, compile the complete list and make sure it has not been run already by checking the website. Please do not open an issue per sample.

**Comment by bioscienceresearch** [comment]
Thanks, SRR11085797 must have been user error. As far as I can tell following hav not been run:

SRR12432009
SRR11806578

**Comment by ababaian** [comment]
Yep, I can slate those for processing but it might take a while before it trickles to the website. If you have an immediate use case I'll post the links to the raw data here once it's ready.
