### ISSUE TITLE
Update contributors list

### ISSUE THREAD

**Issue by victorlin** [ababaian/serratus#250]
> Also we should make a new issue to update the team page with the new authors. Probably start a "Virology" section for Marcos.

_Originally posted by @ababaian in https://github.com/serratus-bio/serratus.io/issues/117#issuecomment-797228813_

TODO:
1. update [CONTRIBUTORS.md](https://github.com/ababaian/serratus/blob/master/CONTRIBUTORS.md)
2. update [teamData.json](https://github.com/serratus-bio/serratus.io/blob/main/src/data/teamData.json)

**Comment by ababaian** [comment]
updated both :+1:
