### ISSUE TITLE
Deal with suppressed phage runs

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#255]
> In the process of generating the manifest files needed, it was noticed that a small number (20) of the assemblies are generated from data that has since been suppressed in ENA. (JGI suppressed a large number of raw data studies a while ago)
> As such we are not able to upload these 20 assemblies as we can’t point to the underlying raw data used to generate the assemblies.
> It may be worth you following up with ENA to find out if these suppressed runs are temporarily suppressed, or fully suppressed, as some data we were affected by was later un-suppressed. So you may be able to upload these assemblies at a later date?

Here are the accessions in question:
`SRR10854512
SRR12613006
SRR12613007
SRR12613009
SRR12613049
SRR12613053
SRR12613091
SRR12613196
SRR12613526
SRR12666045
SRR12689551
SRR12689835
SRR13207416
SRR13208129
SRR13208130
SRR13208236
SRR13208416
SRR13208437
SRR13208515
SRR7690231`

**Comment by ababaian** [comment]
This is unrelated to the current submission/manuscript sets and part of ongoing work. We dropped these with no skin off our back.
