### ISSUE TITLE
Novel viruses identified by Serratus

### ISSUE THREAD

**Issue by aninditaces** [ababaian/serratus#261]
Hello!
Is there a database containing the sequences of the novel viruses identified by serratus?
Thanks very much.

**Comment by rcedgar** [comment]
Palmprints are here: [https://github.com/rcedgar/palmdb](https://github.com/rcedgar/palmdb), you can search a palmprint to find SRA accessions here:[ https://serratus.io/palmid]( https://serratus.io/palmid), in some cases complete contigs may be found in our assemblies (there is currently no index into the assemblies so some manual checking is needed for this last step).

**Comment by aninditaces** [comment]
Thanks very much!
