### ISSUE TITLE
Is Serratus running on most recent SRAs?

### ISSUE THREAD

**Issue by centaria** [ababaian/serratus#263]
Hello Serratus Team, I was wondering if Serratus displays search only from SRAs obtained at the time of the Serratus paper publication or if you guys are running it on newly emerging SRAs since your publication and updating the results? Thank you very much!

**Comment by ababaian** [comment]
Hey @centaria,

We have everything up until Jan 1st 2021 analyzed, the reports and data are online at `s3://lovelywater/` for those runs, we're just a bit slow with propagating the data downstream into  the website and SQL server :'( . If you know the datasets you're looking for you can download them directly by accession.

**Comment by centaria** [comment]
Thank you very much, Artem, this is very helpful. Are you planning to run serratus on the new samples and deposit results?

**Comment by ababaian** [comment]
Yep, it will be run in batches moving forward. I'm hoping to get some of the downstream processing cleaned up into a pipeline to make the update process smoother. Only so many hours in a day though '^_^

**Comment by centaria** [comment]
Thank you very much, Artem. Please keep us posted. What a great work you and the team are doing for the humanity. I’m a big fan. Thank you!
