### ISSUE TITLE
palmID viral RdRp analysis crash

### ISSUE THREAD

**Issue by FBeguier** [ababaian/serratus#265]

**Comment by ababaian** [comment]
is this resolved now?

**Comment by FBeguier** [comment]
Hi, 

I tought it was resolved (it worked for one analysis), that's why I deleted my post. 
But I try antoher one and I just received the same error message.

This is the end of the error message:
![image](https://user-images.githubusercontent.com/117846552/201120649-2679be36-5ea6-4bbf-a0e3-f556177d2c34.png)

**Comment by ababaian** [comment]
welcome to github :) it helps to not delete information and simply close the issue when it's done.

Can you please post the hash link so I can take a look at the full error logs and see what's going on.

**Comment by FBeguier** [comment]
Oops yes, sorry for that !

I'm not a bioinformaticien.. what is the hash link ?

Here is the link of the message I just obtained : 
[(https://serratus.io/palmid?hash=3438969b1ac28e9d40bcd82a923b1771a0f43fb3)](url)

**Comment by ababaian** [comment]
Are you certain the input sequence is an RdRp? `palmscan` does not seem to be retrieving a palmprint domain and MUSCLE is not finding any alignments.

**Comment by ababaian** [comment]
I'm mostly certain it's not an RdRp sequence input, in the closest virus "Mute Swan Tombu", ORF2 is the RdRp (see: https://serratus.io/palmid?hash=b6a0e63f3e1a559c18823852f9e97000284c207b) but the sequence you are inputting matches ORF1, which is another protein.

palmID works strictly for virus RdRp sequences, you will not get any output if you do not enter an RdRp.

**Comment by FBeguier** [comment]
Actually, I don't know, I check different viral sequences for RdRp presence by using Serratus. 

So if I receive this message, it means that there is no RdRp in my sequence ?

**Comment by ababaian** [comment]
That's mostly correct yes, if you REALLY think there should be an RdRp, you can check InterPro which has higher sensitivity: https://www.ebi.ac.uk/interpro/result/InterProScan/

**Comment by FBeguier** [comment]
Ok perfect, thanks a lot for your help !
