### ISSUE TITLE
Tree data

### ISSUE THREAD

**Issue by ellasiera** [ababaian/serratus#272]
Cheers! First of all thank you for creating this amazing resource. I was hoping to use your trees to place my RdRp sequences into with pplacer. Any chance you have the phyml stats.txt or RAxML info file for the trees provided on the website?

**Comment by ababaian** [comment]
I think we have the tree files, but tbh this was a reviewer request and I wouldn't put a whole bunch of weight/trust in it. The palmprint sequence is only good for creating local family-like phylogenetic trees, going beyond that you need longer sequences so the trees we have are kind of ballpark approximations.

If you're OK with that let me know and I can dig into where we have all the files. My suggestion is to use these as a way of pulling out "local" related RdRp and building a phylogeny from longer RdRp.

**Comment by ellasiera** [comment]
Gotcha. No worries. I think I'll generate the trees I need from ICTV sequences and make them + stats files available on my GitHub in case anyone ever asks the same question. Cheers!
