### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by austinreidmanny** [ababaian/serratus#273]
When I navigate to Serratus.io, I am met with a blank page and a login screen. Is this unintentional, or will the website interface be discontinued?

<img width="647" alt="image" src="https://github.com/ababaian/serratus/assets/22330643/a4f38edd-cc25-4c1f-960b-c41f752cdeca">

**Comment by ababaian** [comment]
We've taken it down shortly, there seems to be a CloudFront Outage and we're tracking down a fix.

**Comment by ababaian** [comment]
aaand we're back!
