### ISSUE TITLE
scRNA-seq analysis with Serratus

### ISSUE THREAD

**Issue by malonzm1** [ababaian/serratus#274]
Hi,

I'm performing Serratus/Tantalus analysis with scRNA-seq data. Each sample/fastq file consists of several cells. What I'd like to do is to map the output viral info to an individual cell. Is this possible?

Thanks and good day.

**Comment by ababaian** [comment]
The aligned reads are retained in the `.bam` or `.pro` alignment file, but those contain only biological and not technical sequences. Most likely you would have to go back to the original sequencing dataset and re-process it to single cells and analyze them again.

Serratus is not set-up or intended to work with scRNAseq data, you can try [Vulture](https://www.biorxiv.org/content/10.1101/2023.02.13.528411v1), although I've never used it.
