### ISSUE TITLE
Allow adding public keys to terraform config

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#30]
Right now we have a terraform variable:

    key_name = "jeff@rosario"

This is annoying because:

- You have to log into the console to import the key
- It doesn't support more than one key (eg. for Jeff and Artem both logging in)

What I really want is to use the same format SSH uses:

    public_keys = [
        "ssh-rsa <publickey> jeff@rosario",
        "ssh-rsa <publickey> artem@somewhere"
    ]

Terraform would then ensure that users can log in using these keys.  Probably via user_data, but TBD.

**Comment by mathemage** [comment]
@jefftaylor42 would any of these 2 links help?
- https://www.terraform.io/docs/providers/aws/r/key_pair.html
- https://stackoverflow.com/questions/49743220/how-do-i-create-an-ssh-key-in-terraform

**Comment by jefftaylor42** [comment]
I think this is still an issue.  When we're collaborating on the cluster this afternoon you're going to have to manually go in and add my public key everywhere manually, and that's obviously not ideal.
