### ISSUE TITLE
fatal error: unable to locate credentials

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#33]
One of the instances got a `fatal error: Unable to locate credentials` when we did the 80-instance run.  Why wasn't its role attached, like the others?

**Comment by jefftaylor42** [comment]
This was in `serratus-align`

**Comment by ababaian** [comment]
Solution will be to add a sanity check 'token' at boot-up of each instance to ensure credentials are working.

**Comment by jefftaylor42** [comment]
Just gonna echo the slack conversation here on this issue.

This happened one time out of 80 instances, and we were a little too swamped to look into what actually happened.  I suggest that we just leave this issue for now, and if we manage to reproduce it the next time we process data, we'll look into what's actually happening a little more closely.

Here are some questions we should try answer when that time comes:

- Does the role appear in the EC2 instance console?  (Problem w autoscaling)
- Can credentials be fetched from within the instance? (Problem between role and instance)
- Is there a call (assumeRole?) that failed or can be repeated? (Operation that should have been retried but wasn't)  Is there a log somewhere that records assumeRole calls?
- Is it related to load (gets worse with scaling) or purely random?

**Comment by ababaian** [comment]
In the last pilot run this was irreproducible. It might have been a one time lark. Closing for now.

**Comment by ababaian** [comment]
So this is a critical bug which is causing a lot of problems

Rarely (<1% of the time) when an EC2 node is booting up, it doesn't have the correct credentials attached and is giving us an error 
```Unable to locate credentials. You can configure credentials by running "aws configure".```

We need a unit test of code to run at boot-up in `containers/worker.sh` which can 'test' the credentials, such that if it fails and/or credentials are not there, the instance can self-terminate.

Right now these failed instances are getting a job from the scheduler, and failing in a second, and then asking for the next job, failing and repeating. This results in one error producing a long list of "fails" and halting the cluster.

**Comment by ababaian** [comment]
This is fixed with adding a test download of an s3 token at the start of worker booting.
