### ISSUE TITLE
Implement a "Jump Server" for serratus 

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#38]
# Current process

1. Add my public key to terraform
2. SSH into all the instances
3. Add Artem's public key
4. Run multiple SSH tunnels on my laptop to connect to:
 - Grafana
 - Prometheus
 - Scheduler

# Desired process

Have one machine, a jump server, with everyone's keypairs installed, and a light nginx webserver, with port forwards setup to the instances we need to see.  Then we just need a single ssh tunnel to connect to all our services.

We could also separate it into its own public subnet, and make the rest of our application run in a private subnet, reducing surface area.

**Comment by ababaian** [comment]
This is a 'nice to have' feature, especially since it would prevent from any part of Serratus being exposed to the internet, but it's probably (almost certainly is) overkill for the immediate future. We can return if need be but closing for now.
