### ISSUE TITLE
Reduce disk usage (or dynamically provision) in serratus-dl.sh

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#4]
The SRA's have vastly different sizes, and currently fastq-dump stores them in raw text which appears to be (empirically speaking, sample size = 1) ~8x larger than the files on SRA.  If we keep doing it this way, some of the SRA files will expand to ~220GB for this step.  Here are some possible options to mitigate:

1. As suggested by Artem, dynamically provision and mount EBS volumes with needed storage. (not sure if possible)
2. Give the instances fixed storage and implement a way for the scheduler to assign jobs to instances with available storage (complicated).
3. Stream the files to and from S3 using pipes.  Maybe possible using SRA-Pipeline code as inspiration (though how to do paired-end reads?)
4. ~Use EFS (Elastic File Store).~  EFS bandwidth for bursting is 50KB/s per GB of store data.  You can pay for extra speed but it's not cheap.  Not meant for temporary files like this.
5. Overprovision storage for the instances and just pay for it.  Easy.  EBS is $0.13/TB-hr.  Worst case scenario is two threads, 220GB each, times 2 (unsplit and split) ~= 1TB.  C5.large Spot instances are ~$0.03/hr (OnDemand = $0.085).  So we pay more for storage than compute, but it's not the end of the world.

**Comment by jefftaylor42** [comment]
For option #5, could also use st1 or sc1 HDDs on EBS, which are 1/2 and 1/4 the price respectively, but much, much slower.  We should profile this—it might be a good option.

**Comment by ababaian** [comment]
Start simple and we'll go from there. Let's bring a skeleton to life and we can worry about optimization next : )

**Comment by jefftaylor42** [comment]
Yeah, the post is more of an "I'm putting this down: here are all the things I thought of until now"

**Comment by jefftaylor42** [comment]
I think this is resolved with #d61248bfd3.  We're now streaming the split fq-blocks directly to S3, and serratus-dl looks good with just its 8GB root volume.
