### ISSUE TITLE
Check updated Automation of project `TODO List`

### ISSUE THREAD

**Issue by mathemage** [ababaian/serratus#40]
Hi @ababaian and @jefftaylor42 !

I have updated the preset Automation actions in the project [`TODO List`](https://github.com/ababaian/serratus/projects/1).

I believe this better reflects your needs to manage this project and appears as logical way to assign the preset actions.

Please check in case you disagree with any of the actions and feel free to close this issue when you are satisfied.

Thanks and regards,
@mathemage

**Comment by ababaian** [comment]
Looks good
