### ISSUE TITLE
cov2 pan-genome refinements

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#41]
### Objective
- Refine `cov1` to reduce the level of false-positives and increase alignment specificity
- Reduce the representation of highly homologous sequences (99% sequence identity) in the pan-genome to decrease the alignment space

**Comment by ababaian** [comment]
> From: R. Edgar
> Bowtie2 false-positives are due to poly-Ts which you can easily see with
> grep, plus these three identical sequences which appear to be wrongly
> annotated as rat coronavirus:
> 
> FB764528.1 HV449436.1 CS382036.1.
> 
> These do not align to the other Cov1 sequences and do have a 95%
> identity match to human chromosome X GRCh38.p12  53076622 - 53077743,
> G-protein coupled receptor gene.
> 
> Should mask poly-T as well as poly-A (suggests we have sequences on both
> strands).

- Add FB764528.1 HV449436.1 CS382036.1 to blacklist
- Add poly-T mask to complement poly-A mask

**Comment by ababaian** [comment]
* Remove all sequences shorter than 100 nucleotides (see: JB626510)
This sequence is 56 nucelotides long (remove all sequences under 100 nt), from a patent and largely uncharacterized.

**Comment by ababaian** [comment]
- Add a manual mask for: `JB181528.1:3,111-3,307`

In the pilot run of 9K vertebrate samples, RNA-seq samples from zebrafish containing plasmid transfections are mapping to this area of [`JB181528`](https://www.ncbi.nlm.nih.gov/nuccore/JB626510.1) annotated as infectious bronchitis virus. When BLAST against total database this sequence is a perfect match to `amp[R]`, so there is a partial plasmid sequence  in this artificial sequence.

**Comment by victorlin** [comment]
> Reduce the representation of highly homologous sequences (99% sequence identity) in the pan-genome to decrease the alignment space

Sounds like the goal of #36?

**Comment by ababaian** [comment]
@victorlin yep I think with the code we have at the bottom of #36 that issue is solved, I'm leaving it open until I finish this update.

**Comment by ababaian** [comment]
- Add mask for `CS460762.1:37,177-37,211` and `CS480537.1:37,170-37,220`. These is a short sequence (~40 nt) that is a perfect match to a cloning vector, and all have soft-clips that match the plasmid better.  Also `CS460762.1:30,166-30,243` and `CS480537.1:30,166-30,241`

![Uploading Screenshot from 2020-04-19 19-49-57.png…]()

**Comment by ababaian** [comment]
- Add mask for `MK562374.1:474-542` there is a partial match to `Fusarium arthrosporioides large subunit ribosomal RNA gene, partial sequence `. This is in `ERR1889781` library, a zebrafish RNA-seq.

![Screenshot from 2020-04-19 19-58-25](https://user-images.githubusercontent.com/9220907/79710046-4ebd3100-82b3-11ea-97e7-763a09209ce1.png)

**Comment by ababaian** [comment]
- Add mask for `DL231478.1:43-2,296` matches an expression vector. Sequence is from: `Recombinant raccoon pox viruses and their use as an effective vaccine against feline infectious peritonitis virus disease`

![Screenshot from 2020-04-19 20-58-20](https://user-images.githubusercontent.com/9220907/79712738-36e9ab00-82bb-11ea-95e8-eb34ab3187ba.png)

**Comment by ababaian** [comment]
Next Version of the pan-genome is created. [See notebook entry](https://github.com/ababaian/serratus/blob/master/notebook/200420_cov2_pangenome.ipynb)
