### ISSUE TITLE
Max RAM in EC2 compute nodes

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#44]
Per CONTRIBUTING: "The workhorse for serratus is currently the C5.large EC2 instance on AWS.. Each node has 2 vCPU and 4 GB of memory". 

My bvfilter requires 8GB RAM. Does this rule out the current implementation of bvfilter, or can we run larger nodes if the filter gives a worthwhile efficiency improvement?

**Comment by ababaian** [comment]
we can scale up given `bvfilter` uses shared memory shared memory.
