### ISSUE TITLE
Blacklist implementation

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#47]
The blacklist is a useful resource. Currently it seems to be embedded rather obscurely in script code. Suggest that it be implemented as a plain-text file in the repo with two fields: accession and comment (why it is blacklisted). The full Covid reference would include an annotation (e.g. blacklist=yes) for the benefit of post-processing analysis rather than removing the sequence from the FASTA file. This is forwards-compatible: if a sequence was blacklisted after a dataset was run through bowtie2, the corresponding SAM records can be ignored, e.g. by the summarizer / candidate dataset identification module. The goal of including it in the master FASTA is to consolidate as much useful information as possible in one resource.

**Comment by ababaian** [comment]
We have in effect two blacklists:
1) Accession blacklist: these are entries removed entirely
2) Region blacklist: these are regions of an accession that blacklisted (poly-A/T, poly-G/C, plasmid DNA fragments). Encoded as a bed file. These are N-masked in the final genome.

Each version of the pan-genome can then have both a `accession.blacklist` file and `region.blacklist` file. 

A `BED4` [format file](https://genome.ucsc.edu/FAQ/FAQformat.html#format1), where the "name" field is a quoted string describing why a region is blacklisted will be compatible with both these types of black-lists.

**Comment by rcedgar** [comment]
An accession should be blacklisted if and only if we have evidence it is not coronavirus. IMO bed is not the appropriate format for an accession blacklist because bed is about regions, not a boolean attribute of the entire sequence. A tsv file with two fields is simpler and more natural; with a bed file you have to ask whether the coordinates cover the entire sequence or not.

If there are non-virus sequences embedded in valid virus sequence due to sequencing problems, then these should be N-masked out of a coronavirus reference, and bed or a similar format would be a good solution for that.

Perhaps some valid coronavirus sequence should be masked out sometimes, e.g. when building a bowtie2 index. A bed file indicating regions you should mask if you're making a bowtie2 index makes sense, but I would argue against N-masking valid sequence in a reference that will probably be used for many purposes, not just building mapper indexes.

However, I'm not convinced that any of the valid coronavirus sequence needs to be masked. Poly-As (Ts...) give short false-positive bowtie2 alignments; they can and IMO should be filtered by alignment score (AS:i tag) in the SAM/BAM record, not by masking the reference. The only reason to hard-mask the reference would be if the BAM files got much larger, but that doesn't seem to be the case. It is easier, more flexible, and less error-prone to have a single AS filter than to figure out each type of problematic fragment and deal with it individually.

**Comment by ababaian** [comment]
All blacklist data is now stored as a `bed` file that is defined at genome creation step explicitly.

The `mask.regions.bed.gz` file is in the genome folder containing the information, basic steps are:
- Blacklisted complete accessions : known contaminants
- Blacklisted regions of accessions : known contaminant regions
- Poly-NT Tract (10 nt repeat)
- Dustmasker --window 30
- Dustmasker --window 64

These are then merged and make up the final output file.
