### ISSUE TITLE
bvfilter bugs & fixes

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#51]
I found and fixed some bugs in bvfilter. New binary posted here:

https://drive5.com/tmp/bvfilter.gz

The md5sum of the binary after gunzip should be bac9251f90e8bddb4f07e398a75ccb76.

Below is the bash script I used for testing. Note that the pipeline is single-threaded, uses bvfilter in memory-mapped mode, and uses bowtie2 in unpaired mode (-U) per Issue #50. I will post timing results from this test shortly, probably as an Issue (is there a better way?).

Notice that the -quiet option of bvfilter is required because otherwise it stupidly writes a copyright message to stdout and messes up the SAM header (this bug not yet fixed).

```
#!/bin/bash

SRR=SRR11454614

./bvfilter -load_bitvec cov.bv -output COV_BV

/usr/bin/time -o time.txt \
    | fastq-dump -Z $SRR \
    | ./bvfilter -quiet -search_bitvec /dev/stdin -threads 1 \
        -ref COV_BV \
        -wordlength 18 \
        -sharedmem \
        -output /dev/stdout \
    | bowtie2 -p 1 \
        -x cov1.id99.polyamasked \
        --very-sensitive-local \
        -U /dev/stdin \
    > hits.sam
```

**Comment by ababaian** [comment]
If you're posting data then maybe experiment notebook entry is the way to go

**Comment by rcedgar** [comment]
Ok. Note that I don't do automated notebooks, but can do PDFs. Should I post by doing a commit without  a pull request? Either way, how are collaborators notified? With an Issue, it's prominent, but AFAIK it's not easy to see that there is a new notebook.

**Comment by ababaian** [comment]
You can commit it yes. I'll read it for sure, if there's a key piece of actionable data then we can open an issue regarding the action needed from that.
