### ISSUE TITLE
AWS architecture Diagrams

### ISSUE THREAD

**Issue by Bluestreak2k5** [ababaian/serratus#52]
We will need AWS architecture diagrams to be able to share and understand architecture meetings. These need to be detailed, including VPC, subnets, Services being called. They will be able to provide much quicker analysis and assistance if you have this.

Take a look at these:
https://www.edrawsoft.com/template-aws-network-diagram.php
https://medium.com/@warren2lynch/aws-architecture-diagram-with-2019-new-icons-over-50-examples-d401a76c6d5c

Make 3 diagrams:
1. Detailed on DL Filter with the end at S3
2. Detailed on align nodes with the start at the S3.
3. Overall diagram, but can be a little less detailed.

Store all 3 in github, they can be used in meetings with AWS.

**Comment by ababaian** [comment]
See: https://github.com/ababaian/serratus/blob/master/CONTRIBUTING.md#bioinformatics-pipeline
