### ISSUE TITLE
Create S3 VPC endpoint

### ISSUE THREAD

**Issue by Bluestreak2k5** [ababaian/serratus#53]
Goto VPC, Gateway endpoints, Create a s3 gateway endpoint. Create a dynamo endpoint too if your using that.

This will increase speed and reduce cost with reducing s3 calls going through IGW.

**Comment by ababaian** [comment]
Currently there are two relevant S3 buckets:
- The work or scratch bucket is defined at boot-up in [`terraform/bucket/main.tf`](https://github.com/ababaian/serratus/blob/master/terraform/bucket/main.tf)
- There is the static `s3://serratus-public/` bucket where final output is stored (defined in terraform/main/main.tf)

Creating an S3 gateway endpoint would make sense, most importantly for the work bucket which is created at `terraform apply`.

**Comment by Bluestreak2k5** [comment]
This isn't a bucket setting, this is a VPC setting.

Currently without this endpoint any S3 traffic is going through the IGW and your paying egress charges. Setting up an S3 gateway endpoint, creates a private endpoint to s3.amazonaws.com through amazon's network. It should reduce costs on network traffic.

**Comment by ababaian** [comment]
I'm trying to figure out which VPC the cluster uses

**Comment by Bluestreak2k5** [comment]
You might be launching it in AWS default VPC and not your own. You must specify it in the spot deployment. If your using AWS VPC then you can close this, but I didn't think you were.

**Comment by ababaian** [comment]
Artur worked his magic on the back-end, this may have helped. Still missing a formal definition in `terraform` but we can call it tentatively done.
