### ISSUE TITLE
Testing bvfilter

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#54]
What else need to happen to test a pipeline with bvfilter? I'm assuming the binary & documentation I've delivered is enough and this is handed off to some combination of Artem & Jeff, please let me know if there is something else I can / should do.

I see Artem's point that the filter can easily be inserted immediately after fastq-dump on a decompression node.

(A) If you train using the host genome as a negative control, this will discard ~99.5% of the reads. 

(B) If you train on the positive pan-genome only, it will discard ~90% of the reads. 

Thus, with (B) ~20x more reads are passed by the filter, but this is still a 10x reduction in the amount data compared to no filter (I forgot to mention this on the status call today). Obviously, this also has the advantage that we don't need a different filter for each host and we don't need to implement infrastructure to ensure that the correct filter is used for each host species.

Possibly, (B) this would also increase sensitivity of the filter to viruses, but I strongly doubt it. Including human discards ~10% of the 18mer seeds found in the pan-genome. It seems very likely that the 90% of the seeds which remain will be enough to find all, or almost all, datasets with viruses. Note that cannot be checked by hold-out validation because the prior expectation is that most related viruses will be found, the question is whether there are any pathological [sic] cases where a novel virus matches the pan-genome almost exclusively in the 10% of the seeds which are also found in the host with almost no matches in the remaining 90%. Perhaps this happens with certain families like pox which are very similar to human, but these would be excluded from the pan-genome anyway.

I guess the question is: how does the cost compare with & without using the host as a negative control? This is easy to test once you have a bvfilter pipeline. If the cost saving of (A) is small, then (B) is clearly better. If the cost saving of (A) is large compared to (B), then (A) is probably the way to go because the cost in sensitivity is probably negligible.

**Comment by rcedgar** [comment]
Can @ababaian provide meta-data for the runs in 200423_ab_cov2r to indicate whether they are TP or FP? This is helpful for testing. Looks like some have spike-in decoy reads (reversed non-complemented) if so a few details would also be helpful. Thanks!

**Comment by ababaian** [comment]
The data is all 'real' data. The entire meta-data for those files is provided in the SraRunInfo Table for them which you can find [here](https://serratus-public.s3.amazonaws.com/sra/testing_SraRunInfo.csv) The `ScientificName` will tell you the species of origin. These are all RNA-seq, and the SARS-cov-2 is metatranscriptomics.
