### ISSUE TITLE
Search the Zoonotic Reservoir for SARS-CoV-2

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#55]
## Batch 1: Searching the Zoonotic Reservoir for SARS-CoV-2

See this [preprint](https://www.biorxiv.org/content/10.1101/2020.04.22.046565v1).

### Steps
- [x] Create a list of all species that are potentially infected by SARS-CoV-2 (SARS2-tropic). Find the Taxonomy ID for each of these species.
- [x] Generate an SRA RunInfoTable for all RNA-seq and meta-transcriptomics data from these species. This is our Batch 1.
- [ ] Integrate the `bvfilter` as a CoV+ filter only. This will keep memory use low and work across species with ~10-fold increase in processing. #54 
- [x] Use improved run statistics for discriminating + and - libraries #57 
- [ ] % Hand off potential CoV+ libraries to assembly folks to build contigs from these libraries
- [ ] % Identify if any CoV from SARS2-tropic species (new or already defined) are likely to recombine with SARS-COV-2 and thus cause secondary pandemics.

% open-ended and may require additional time.

I think we can get this batch done in a few days after the AWS credits come in.

### Deadline
First set of credits are expected ~May 1st. This should be ready to go on that date.

**Comment by KristinaGagalova** [comment]
Starting from the S1 Table in the paper Liu et al., 2020, I've downloaded the list of species (excluding Homo sapiens) that are possibly susceptible to Sars-Covid.
[ListSpecies.ACE2receptor2.txt](https://github.com/ababaian/serratus/files/4561921/ListSpecies.ACE2receptor2.txt)

Using the following script and the esearch/efetch utilities 
```
#!/bin/sh

set -u
TAXLIST=("Pan troglodytes" "Pan paniscus" "Gorilla gorilla gorilla" "Nomascus leucogenys" "Pongo abelii" "Macaca mulatta" "Macaca fascicularis" "Macaca nemestrina" "Cercocebus atys" "Mandrillus leucophaeus" "Papio anubis" "Theropithecus gelada" "Chlorocebus sabaeus" "Rhinopithecus roxellana" "Piliocolobus tephrosceles" "Callithrix jacchus" "Sapajus apella" "Cebus capucinus imitator" "Aotus nancymaae" "Saimiri boliviensis boliviensis" "Propithecus coquereli" "Oryctolagus cuniculus" "Ochotona princeps" "Mesocricetus auratus" "Cricetulus griseus" "Peromyscus leucopus" "Peromyscus maniculatus bairdii" "Jaculus jaculus" "Ictidomys tridecemlineatus" "Sus scrofa" "Globicephala melas" "Lagenorhynchus obliquidens" "Orcinus orca" "Tursiops truncatus" "Delphinapterus leucas" "Monodon monoceros" "Neophocaena asiaeorientalis asiaeorientalis" "Lipotes vexillifer" "Physeter catodon" "Balaenoptera acutorostrata scammoni" "Bos taurus" "Bos indicus" "Bos indicus x Bos taurus" "Bison bison bison" "Odocoileus virginianus texanus" "Bos mutus" "Bubalus bubalis" "Ovis aries" "Capra hircus" "Rousettus aegyptiacus" "Vombatus ursinus" "Phascolarctos cinereus" "Trichechus manatus latirostris" "Equus caballus" "Equus przewalskii" "Equus asinus" "Ceratotherium simum simum" "Canis lupus familiaris" "Canis lupus dingo" "Vulpes vulpes" "Ailuropoda melanoleuca" "Ursus maritimus" "Ursus arctos horribilis" "Zalophus californianus" "Eumetopias jubatus" "Callorhinus ursinus" "Odobenus rosmarus divergens" "Phoca vitulina" "Neomonachus schauinslandi" "Mustela putorius furo" "Mustela erminea" "Enhydra lutris kenyoni" "Felis catus" "Lynx canadensis" "Acinonyx jubatus" "Puma concolor" "Panthera pardus" "Panthera tigris altaica" "Manis javanica")
#TAXLIST=("Gorilla gorilla gorilla" "Nomascus leucogenys")
#TAXLIST=$1

for TAX in "${TAXLIST[@]}" ; do
nam=$(echo $TAX | sed 's/ /_/g')
echo getting RunInfo for: $TAX
   GENOME=$(esearch -db sra -query "$TAX"[orgn] |
       efetch -format runinfo | tee ${nam}.esearch.RunInfo.all.txt)
echo "processing ${nam}"
grep "TRANSCRIPTOMIC" ${nam}.esearch.RunInfo.all.txt > ${nam}.esearch.RunInfo.out
#rm "${TAX}.esearch.RunInfo.tmp"
done
```
I have downloaded the SRA InfoTable for all the species, selecting by "TRANSCRIPTOMICS" features.
Data to be uloaded HERE

**Comment by ababaian** [comment]
Experiment is now complete. Data is currently on `s3://serratus-public/out/200505_zoonotic/` See notebook entries from that date for details of the run.
