### ISSUE TITLE
Assembly protocol of COV sequences

### ISSUE THREAD

**Issue by JustinChu** [ababaian/serratus#65]
Develop prototype generic assembly pipeline for cov+ flagged libraries.

First pass assembly may only require assembly of classified reads. Divergent sequence may require an alterative targetted assembly aproach similar to Kollector.

Once protocol is evaluated integrate into serratus pipeline.

**Comment by rcedgar** [comment]
@JustinChu please see #71 and #72. What do you think? Would you like to take on these tasks?

**Comment by JustinChu** [comment]
Sounds good. I'll add the assemblers I plan on testing to #71. #72, especially for testing/evaluating for performance in assembling new/divergent strains will probably need some refinement.

**Comment by ababaian** [comment]
coronaSPAdes and big guns was the move in the end.
