### ISSUE TITLE
Port/test `serratus-dl` and `serratus-align` containers to ARM (a1.instance)

### ISSUE THREAD

**Issue by mathemage** [ababaian/serratus#8]
Build `bowtie2` on ARM, to take advantage of ~1/2 price A1 instances. Also `samtools` and `blastn`.

_Originally posted by @ababaian  in 
https://github.com/ababaian/serratus/issues/5#issue-589616145_

### ordered priority 
- [x] `samtools` on ARM
- [ ]  `sratoolkit` on ARM
- [x] `bowtie2` on ARM

**Comment by mathemage** [comment]
@ababaian What do you mean by "Also `samtools` and `blastn`"? Are these identical tasks but for the other tools/programs?

If so, would you agree to extract it out to 2 new separate issues? The smaller the issues, the more manageable and "mergeable" they are.

**Comment by jefftaylor42** [comment]
I think it's all one task.  The A1 instances on AWS appear to be much cheaper (like half), but the software doesn't currently run there since they're ARM.  It doesn't help us if some tools work and some don't so I think this should stay as one issue.

**Comment by mathemage** [comment]
@jefftaylor42 ok, your call. I don't understand the context enough to make a decision on this.

**Comment by mathemage** [comment]
@jefftaylor42 ...renaming the issue then

**Comment by jefftaylor42** [comment]
`bowtie2` is the aligner we're using for the human genome project, but I believe for the SARS-CoV-2 project we'll need a different set of tools.

`samtools` does data conversion, so it might be needed in both projects.

**Comment by jefftaylor42** [comment]
This task is potentially really high effort and low reward, so very low priority.

**Comment by mathemage** [comment]
> This task is potentially really high effort and low reward, so very low priority.

Can you set it as a tag then? Is there any option to set priorities of issues here?

**Comment by jefftaylor42** [comment]
https://gitlab.com/arm-hpc/packages/-/wikis/packages/bowtie2

**Comment by codeistpl** [comment]
I compiled samtools on A1 and checked that main Dockerfile is running fine.

**Comment by codeistpl** [comment]
serratus-dl image cannot build on a A1 because of sra-toolkit.

**Comment by ababaian** [comment]
maybe we come back to `serratus-dl` then, how about `serratus-align`?

**Comment by codeistpl** [comment]
docker is installing a bowtie2 for x86, i think I can compille it for aarch64 but, it depends on intel threading library, and version is unspecified. As I will found a tbb version that is suitable for bowtie2 I will make a build. :-)

**Comment by codeistpl** [comment]
`serratus-align` node can run on A1. 'arm-dev branch' but this should work also for x86 :-) just I did not checked that yet :-)

**Comment by ababaian** [comment]
Hey @codeistpl, we don't need `magic-blast` implemented currently. First metrics showed that `bowtie2` will be more sensitive. I think moving on to phase 2 of this and optimizing compilation for A1 against a bench-mark will be the move from now.

**Comment by ababaian** [comment]
@codeistpl How is this coming along? Have you been able to test that the `serratus-align` container can build on ARM architecture?
