### ISSUE TITLE
Datasets in 200505_zoonotic which should be excluded?

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#84]
Transcriptomic analysis of the Novel Middle East Respiratory Syndrome Coronavirus (MERS-CoV):
SRR1193957-8

Transcriptional response to SARS-CoV-2 infection in ferret:
SRR11517855-62

**Comment by ababaian** [comment]
These are "obvious" but should not be excluded. We should assemble all known libraries as well to maximize capturing genetic diversity.

**Comment by rcedgar** [comment]
Yes -- you're right, of course. I guess the correct fix is to annotate the host as human not ferret or whatever.

**Comment by ababaian** [comment]
Correct, we want host of virus not host of the library necessarily.
