### ISSUE TITLE
Instance doesn't signal the scheduler when shutting down

### ISSUE THREAD

**Issue by jefftaylor42** [ababaian/serratus#9]
Steps to Reproduce:

1. SSH into a running serratus-dl instance and run `docker stop serratus-dl`.
2. SSH into a running serratus-dl instance and run `sudo shutdown -h now`
3. Decrease the size of a running serratus-dl ASG from 1 to 0.

Expected behaviour:

In all cases, the instance should send a "terminated" message to the scheduler, before shutting down cleanly.  (which tells the scheduler it can reschedule that job)

Actual behaviour:

The "terminated" signal isn't sent.

In case 1, Docker waits the full 10 seconds for the program to receive its signal, before hard-killing it.

**Comment by jefftaylor42** [comment]
So this is an interesting bug because there are several layers that all need to be working for the desired behaviour in Case 3 to work as expected.

- Our worker.sh script needs to correctly trap and handle SIGTERM
- Docker needs to send SIGTERM to worker.sh
- The OS needs to tell docker to `stop` (send sigterm) when it shuts down, and not `kill` (send sigkill)
- The ASG needs to shut down, not terminate the instance when scaling in.

Any debugging effort should start at the lowest levels (the first bullet points here)

**Comment by mathemage** [comment]
@jefftaylor42 
FYI I am looking into this now...

**Comment by mathemage** [comment]
@jefftaylor42 @ababaian Do you run Dockerfiles from the root folder of the repository this way?
```bash
$ docker build -f docker/Dockerfile -t serratus .
```

I couldn't find any instructions on building docker images, maybe we should add them to `README.md`.

**Comment by ababaian** [comment]
See new [Dockerfile README](https://github.com/ababaian/serratus/tree/master/docker)

**Comment by jefftaylor42** [comment]
Update: the first `echo` statement in our error handle does make it to cloudwatch logs:

https://github.com/ababaian/serratus/blob/0b0bc94e26402c6e88ee6af3f1a3c41a8768ce06/scripts/worker.sh#L25

So the handler IS being called during scale-in.  But for some reason the second line doesn't appear in the logs, and the `curl` (line 3 in the handler) doesn't appear to get called.

**Comment by ababaian** [comment]
@mathemage have you followed-up on this at all?

**Comment by mathemage** [comment]
@ababaian Sorry, I haven't got to your project so far. Intended to, but never managed to get back to it on weekends (I have tight deadlines at university these days).

I'm gonna have a look at it on Saturday, is that okay with you guys? 

Or do you need to get this going sooner? If so, you can just re-assign this issue to someone else.

Thanks & take care!

**Comment by ababaian** [comment]
Saturday works, just needed an update where you're at.

**Comment by ababaian** [comment]
Bump: any luck with this issue @mathemage

**Comment by mathemage** [comment]
> Bump: any luck with this issue @mathemage

I didn't have time to get it, I can work on this on weekends only. I have created thought a [PR](https://github.com/ababaian/serratus/pull/60) for this issue.

**Comment by ababaian** [comment]
It's alright, I think just don't assign something to yourself unless you're actively working on it as this means other people don't work on it and this is a higher priority issue.

**Comment by mathemage** [comment]
> It's alright, I think just don't assign something to yourself unless you're actively working on it as this means other people don't work on it and this is a higher priority issue.

Other's can work on the issue as well - that's normal in open source.

If it's a higher priority, I'll unassign myself.
