### ISSUE TITLE
Identify desired assembler output

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#91]
We want to harmonize the output directory/tarball format for the various pipelines that will be tested. This will make it easier to compare their results, and develop down-stream pipeline components. Some of this will require reformatting of files (e.g. FASTA deflines).

Please contribute ideas to the Wiki:
https://github.com/ababaian/serratus/wiki/Serratus-Assembly

**Comment by ababaian** [comment]
Is this sufficiently defined in #130 to close this issue?

**Comment by rcedgar** [comment]
Let's defer until Jun 2-3 after benchmark to review what the chosen assembler can generate.

**Comment by rcedgar** [comment]
@taltman we seem to have converged on assembly output, can we close this issue now?
