### ISSUE TITLE
Make sure BCB2 team is on-boarded

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#92]
Everyone participating from BCB2 should:

* Have sent GitHub handle to Artem
* Joined Serratus Slack

**Comment by taltman** [comment]
I think we have everyone on Slack, but is everyone now have access to the GitHub repo? Is there anyone that still needs to send you their GitHub handle, @ababaian ?

**Comment by taltman** [comment]
Are Aria & Kishori on GitHub now, @ababaian ?

**Comment by ababaian** [comment]
yes, check your spam folder for github emails if you didn't get it.

**Comment by ababaian** [comment]
Any remaining tasks here?
