### ISSUE TITLE
Incorporate auN metric from Heng Li

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#93]
See full description here:
http://lh3.github.io/2020/04/08/a-new-metric-on-assembly-contiguity

**Comment by rcedgar** [comment]
Doubt of much value to us because auN is for longer genomes with many contigs, my guess is that with viruses we'll typically get 1, 2 or 3 contigs.

**Comment by ababaian** [comment]
Good to close for now?

**Comment by ababaian** [comment]
This is closed by the use of `checkV` #100
