### ISSUE TITLE
Reference-guided assembly pipeline

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#94]
@ababaian has mentioned that we will pursue both reference-based and reference-free (i.e., de novo) assembly pipeline approaches. I'm not clear if on the call today we discussed an concrete pipeline for reference-based assembly. Please reply if you are interested in trying something here.

**Comment by rcedgar** [comment]
I have written a prototype reference-guided assembler with the goal of delivering Serratus-specific features that are not in existing tools AFAIK, I will be posting some draft assemblies soon.

**Comment by taltman** [comment]
@cmorganl has some ideas in this area. Jump in!

**Comment by ababaian** [comment]
Good to close for now?

**Comment by rcedgar** [comment]
Sure. I think we may revisit this for short reads/low coverage. SNW.
