### ISSUE TITLE
Sus scrofus samples with high or low virus abundance

### ISSUE THREAD

**Issue by taltman** [ababaian/serratus#96]
I forget who exactly mentioned this, but there are known samples with high levels of coronavirus, and those with low abundance. Can someone please update the Assembly wiki page with the context & accessions? Thanks!
https://github.com/ababaian/serratus/wiki/Serratus-Assembly

**Comment by ababaian** [comment]
## Pig high coverage samples matching PEDV
```
SRR10829958
SRR10829957
SRR10829954
SRR10829953
SRR10829952
SRR10829951
```

## Pig low coverage samples matching IBV
```
SRR10951665.summary:acc=pan_genome;hits=866;len=30000;depth=2.92;pctid=95.4;tax=?;cov=1.0000;coverage=...............................O;desc=Pan-genome;
SRR10951664.summary:acc=pan_genome;hits=1142;len=30000;depth=3.84;pctid=97.8;tax=?;cov=1.0000;coverage=OoOOOOooo.OoOoooooooooooOooooOOO;desc=Pan-genome;
SRR10951663.summary:acc=pan_genome;hits=746;len=30000;depth=2.51;pctid=95.1;tax=?;cov=1.0000;coverage=o..oo..............o........oooO;desc=Pan-genome;
SRR10951662.summary:acc=pan_genome;hits=1182;len=30000;depth=3.98;pctid=98.1;tax=?;cov=1.0000;coverage=OooOOOOooOOoOOoOOooOoooOooOoOOOO;desc=Pan-genome;
SRR10951661.summary:acc=pan_genome;hits=677;len=30000;depth=2.28;pctid=94.8;tax=?;cov=1.0000;coverage=............................o..O;desc=Pan-genome;
SRR10951660.summary:acc=pan_genome;hits=1047;len=30000;depth=3.52;pctid=97.9;tax=?;cov=1.0000;coverage=OOoOOO.oooOOooooooooooOOOOOoOOOO;desc=Pan-genome;
SRR10951659.summary:acc=pan_genome;hits=1058;len=30000;depth=3.56;pctid=94.6;tax=?;cov=1.0000;coverage=ooooooooo.oooooOoo.ooooo.oooOoOO;desc=Pan-genome;
SRR10951658.summary:acc=pan_genome;hits=1982;len=30000;depth=6.67;pctid=98.1;tax=?;cov=1.0000;coverage=OOOOOOOOOoOoOOOOOooOOoOOooOOOOOo;desc=Pan-genome;
SRR10951657.summary:acc=pan_genome;hits=1139;len=30000;depth=3.83;pctid=94.0;tax=?;cov=1.0000;coverage=Ooooooooooo.ooOooo.ooooo.oooOoOO;desc=Pan-genome;
SRR10951656.summary:acc=pan_genome;hits=2361;len=30000;depth=7.95;pctid=98.2;tax=?;cov=1.0000;coverage=OOOOOOooOoOoOoooOooOooOOooOOOOOo;desc=Pan-genome;
SRR10951655.summary:acc=pan_genome;hits=1011;len=30000;depth=3.4;pctid=94.7;tax=?;cov=1.0000;coverage=oo.o.o......o..o...oo.oo..o.oooO;desc=Pan-genome;
SRR10951654.summary:acc=pan_genome;hits=1830;len=30000;depth=6.16;pctid=98.0;tax=?;cov=1.0000;coverage=OoOOOOooooOoooooOooOOoOOooOoOOOo;desc=Pan-genome;
```

**Comment by taltman** [comment]
@rcedgar I noticed that you closed this issue. Let's use the Serratus Assembly Github Project work-flow, where tasks that are completed are reviewed before they get marked as done & closed. For example, I need to move this content to the wiki, and then it is closed. Otherwise, people have to fish around closed issues trying to find snippets of information. Thanks!
For your convenience, here is a link to the Project view:
https://github.com/ababaian/serratus/projects/2

**Comment by rcedgar** [comment]
FYI, nothing against the work-flow approach but I don't understand it and and don't have time to learn it right now.

**Comment by taltman** [comment]
All you have to do is drag the "card" that represents the issue from the "TODO" or "In Progress" column to the "Review in progress" column. Not exactly particle physics. :-p

**Comment by ababaian** [comment]
How about for issues. If you open it. You close it. Or we @ bump you to close it if you're slacking

**Comment by rcedgar** [comment]
That sounds like good etiquette, probably I shouldn't have closed @taltman's issue; I was trying to cut down on the number of open issues,

**Comment by taltman** [comment]
@ababaian I like that protocol! I will document it on the wiki as part of closing this issue. Another alternative is to reassign the issue to the person that you want to review the work, to sign off that it's complete and then can close the issue.
@rcedgar No worries! We're figuring out how to pilot this plane as we're building it. :-)

**Comment by ababaian** [comment]
Benchmark defined in #130 now
