### ISSUE TITLE
Assembly QC by aligning reads to contigs

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#99]
On the assembly video call today someone mentioned a method for measuring assembly quality by aligning reads to contigs. Can someone volunteer to do this for the reference assemblies in #89? Either way can someone post link(s) to methods here in this issue?

**Comment by JustinChu** [comment]
Not strictly measuring assembly quality. Most tools help detect misassemblies from read data or other sources and even help correct these misassemblies.
[misSequel](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4542784/)
[MEC](https://ieeexplore.ieee.org/abstract/document/8496792)
[PECC](https://www.sciencedirect.com/science/article/abs/pii/S1476927117301974)

The metric for measuring quality would simply be the number of misassemblies or perhaps misassembly types.

Please add to the list if you find any more tools.

**Comment by taltman** [comment]
I think @cmorganl might have some good ideas here.
